import type { AuthoredPage } from '../types';

/**
 * baro_hank, amateur weather station, back porch, reports to nobody.
 *
 * Rule for these: a reading and its units open the thought. If a line would
 * survive without the number in front of it, it belongs to somebody else.
 */
export const HANK_PAGES: AuthoredPage[] = [
  {
    slug: 'hank-station',
    title: 'Porch Station 3',
    author: 'baro_hank',
    hour: 6,
    layout: 'report',
    tag: 'homepage',
    updated: '02 Feb 1999',
    search: 'amateur weather station barometer porch readings',
    teaser: 'One barometer, one thermometer, one rain gauge that a squirrel keeps knocking over. Reports to nobody and posts anyway.',
    paragraphs: [
      `Station 3 is a barometer, a max-min thermometer, and a rain gauge bolted to the porch rail at four feet, which is wrong by the book and right for my porch.`,
      `29.92 inches and steady this morning. That is the number the whole page hangs on, so if you read nothing else, read that the pressure was flat at six and I did not trust it.`,
      `I say Station 3 because the first two are in a box in the cellar. Station 1 froze and split. Station 2 I dropped. This one has lasted a year, which for me is a record and for a barometer is Tuesday.`,
      `Nobody asked for these readings. I put them up because the radio forecast covers three counties at once and my porch is not three counties, it is one porch, and the porch is usually right about the porch.`,
      `The gauge reads a tenth low when the squirrel has been at it. I note the squirrel in the log because a reading with a known error beats a clean number you cannot trust. Next reading at noon.`,
    ],
    footnote: `Station 3. Elevation 612 feet, give or take the porch.`,
    related: [{ label: 'The pressure log', url: 'rn:n-hank-pressure-log' }],
  },

  {
    slug: 'hank-pressure-log',
    title: 'Porch Station 3: the barometer, hour by hour',
    author: 'baro_hank',
    hour: 7,
    layout: 'manifest',
    tag: 'station log',
    updated: '17 Feb 1999',
    search: 'barometric pressure falling log hourly readings',
    teaser: 'A day of readings on the hour. The point is not any one number, it is the direction they walk.',
    paragraphs: [
      `A single pressure reading tells you almost nothing. Six of them in a row tell you what the sky is about to do, and that is the only forecast I actually believe.`,
      `Reading the table below: time, then inches of mercury, then what I did about it. The doing is the part the radio never gives you.`,
      `The rule I go by is simple and it has cost me nothing to keep. Falling fast means bring it in. Falling slow means watch it. Flat means the sky has not decided and neither should you.`,
    ],
    bullets: [
      `06:00: 29.92, flat, wrote it down and doubted it`,
      `08:00: 29.88, first real drop, brought the cushions in`,
      `10:00: 29.81, falling steady, told the neighbour who did not care`,
      `12:00: 29.74, falling fast now, this is the one that counts`,
      `14:00: 29.70, still going, closed the cellar window`,
      `16:00: 29.71, the turn, and the turn is always quieter than the fall`,
    ],
    footnote: `Station 3. Trend beats value. Next full table Sunday.`,
    related: [{ label: 'The station itself', url: 'rn:n-hank-station' }],
  },

  {
    slug: 'hank-the-storm',
    title: 'Porch Station 3: the one I got right',
    author: 'baro_hank',
    hour: 20,
    layout: 'report',
    tag: 'station log',
    updated: '11 Jan 1999',
    search: 'august storm barometer forecast right prediction',
    teaser: 'He called the August storm off his porch six hours before the radio did. He will tell you about it whether you ask or not.',
    paragraphs: [
      `I am going to tell the storm story once, properly, so I can stop telling it in pieces every time somebody new finds this page.`,
      `29.60 and dropping a hundredth every twenty minutes. I have never seen the needle move like that before or since, and when a needle moves like that you do not need a degree, you need a basement.`,
      `The radio said scattered showers into the evening. I put a note on this page at two in the afternoon that said the evening was going to be a lot more than scattered, and I gave a time, because a forecast without a time is just a mood.`,
      `It came in at eight, near enough to my time that I have been insufferable about it for five months. The county took a tree through the Henderson roof and lost the power to half the valley until morning.`,
      `Here is the honest part, since honesty is the only thing that makes the bragging bearable. I have been wrong plenty. The porch was right that day because the pressure told the truth and I happened to be sitting next to it. Next reading whenever the needle asks for one.`,
    ],
    quote: `a forecast without a time is just a mood`,
    footnote: `Station 3. Filed the storm properly, Jan 1999.`,
  },

  {
    slug: 'hank-the-quiet-sky',
    title: 'Porch Station 3: nothing, for a week',
    author: 'baro_hank',
    hour: 13,
    layout: 'blotter',
    tag: 'station log',
    updated: '05 Mar 1999',
    search: 'high pressure calm week boring weather log',
    teaser: 'A high sat over the valley for seven days. He logged every flat reading anyway, and explains why the flat ones matter most.',
    paragraphs: [
      `12:00. 30.10 and it has been within four hundredths of that number for six days, which is the most boring the sky ever gets and the most useful the log ever is.`,
      `A high like this parks over the valley and sits. The air stops arguing. You get cold clear nights that steal your tomatoes and blue days that fool people into leaving the house without a coat.`,
      `I keep logging the flat numbers because a week of known-flat is the ruler I measure the next drop against. When 30.10 finally breaks, I will know exactly how fast, because I will have six days of it standing still to compare against.`,
      `The squirrel has moved on to the Hendersons' feeder, so the gauge is honest this week for a change. Small mercies. Next reading at six, and it will say 30.10, and that will be the news.`,
    ],
    footnote: `Station 3. Boring is a measurement too.`,
  },

  {
    slug: 'hank-frost-warning',
    title: 'Porch Station 3: frost tonight, probably',
    author: 'baro_hank',
    hour: 19,
    layout: 'telegram',
    tag: 'forecast',
    updated: '28 Apr 1999',
    search: 'frost warning clear calm night dew point garden',
    teaser: 'A short one. Clear sky, dropping dew point, no wind. Cover the garden.',
    paragraphs: [
      `19:00. 30.05, clear, wind gone flat, dew point sliding toward the frost line, which is the exact recipe I have watched turn a garden black overnight.`,
      `Clear sky lets the day's heat leave straight up with nothing to hold it. No wind means no mixing, so the cold pools low, right where your seedlings are. High pressure means it will not blow off before dawn.`,
      `Cover the tender rows tonight. Old sheets, cardboard, anything that traps a little ground heat. Take it off after the sun is up or you cook them, which is a different way to lose the same plants.`,
      `I could be wrong. If a breeze comes up after midnight the whole thing is off and you covered the garden for nothing, which is the cheapest kind of wrong there is. Next reading at first light.`,
    ],
    footnote: `Station 3. Cover the rows. Better a wasted sheet than a dead row.`,
  },

  {
    slug: 'hank-radio-vs-porch',
    title: 'Porch Station 3: why I trust the needle',
    author: 'baro_hank',
    hour: 9,
    layout: 'card',
    tag: 'notes',
    updated: '14 Feb 1999',
    search: 'local weather versus broadcast forecast trust barometer',
    teaser: 'Not a forecast, an argument. The broadcast is for a region. The porch is for the porch.',
    paragraphs: [
      `Somebody wrote in to ask, politely, why a man with a radio bothers with a barometer at all. Fair question, so here is the answer as plainly as I can put it.`,
      `The broadcast forecast is built for the whole listening area, which is fields and lakes and three towns and a ridge, all averaged into one cheerful sentence. My porch is on the wrong side of the ridge from the airport they measure at, and the ridge does not care what the average is.`,
      `A barometer does not forecast the region. It measures the actual air sitting on the actual porch right now, and air that is leaving in a hurry is leaving in a hurry regardless of what the average is doing forty miles east.`,
      `So I use both. The radio tells me what the big weather is thinking. The needle tells me what my night is going to be. When they disagree, out here, the needle has the local vote, and the local vote is the one that gets my tomatoes.`,
    ],
    footnote: `Station 3. Both instruments. One porch.`,
  },

  {
    slug: 'hank-the-broken-gauge',
    title: 'Porch Station 3: the squirrel situation',
    author: 'baro_hank',
    hour: 11,
    layout: 'blotter',
    tag: 'station log',
    updated: '21 Mar 1999',
    search: 'rain gauge squirrel error correction honest reading',
    teaser: 'A rain gauge, a squirrel, and a small lesson about admitting your instrument is compromised.',
    paragraphs: [
      `11:00. Gauge reads 0.4 inches for last night. The real number is closer to 0.5, because the squirrel tips a tenth out of it every time he uses the rim as a diving board, and I have watched him do it.`,
      `I could shim the gauge, cage it, move it. I have tried all three. The squirrel is smarter than the gauge and only slightly dumber than me, and the arms race is not one I am winning on a porch budget.`,
      `So instead I log the squirrel. Every reading affected gets a note. A number you know is a tenth low is worth more than a number you pretend is perfect, because you can correct the honest one and you can only be fooled by the clean one.`,
      `That is the whole philosophy of this station, if a porch can have a philosophy. Measure what you can, note what you cannot, never dress a guess up as a fact. Next reading at two, squirrel permitting.`,
    ],
    footnote: `Station 3. The squirrel is winning and I respect it.`,
  },

  {
    slug: 'hank-wind-from-the-east',
    title: 'Porch Station 3: when the wind backs east',
    author: 'baro_hank',
    hour: 16,
    layout: 'report',
    tag: 'notes',
    updated: '08 Apr 1999',
    search: 'east wind backing weather change rain valley',
    teaser: 'A rule of thumb about wind direction that has held up over the valley for a year of watching.',
    paragraphs: [
      `16:00. Wind has backed around to the east and the pressure is easing off, and out here that pairing has meant weather within the day roughly four times out of five.`,
      `West wind in this valley is the fair-weather wind. It comes down off the high ground dry and it usually means the sky is settled for a while. You learn to relax a little when the flag points the same way as the road.`,
      `East is the other story. East wind means the air is coming up the valley off the lower ground, damp, and it tends to arrive just ahead of the pressure sagging. When the flag swings east and the needle starts down together, I stop what I am doing and pay attention.`,
      `This is a porch rule, not a law. Four times out of five is not five times out of five, and the fifth time makes a fool of anyone who forgets it. But a rule that pays off four times in five is worth keeping written down. Next reading at six.`,
    ],
    quote: `west is the fair-weather wind, east is the other story`,
    footnote: `Station 3. East wind, needle down, pay attention.`,
  },

  {
    slug: 'hank-the-anomaly',
    title: 'Porch Station 3: the reading I could not place',
    author: 'baro_hank',
    hour: 3,
    layout: 'blotter',
    tag: 'station log',
    updated: '18 Mar 1999',
    search: 'strange pressure jump night clear sky unexplained reading',
    teaser: 'One night the needle jumped and nothing in the sky explained it. He wrote it down and marked it open.',
    paragraphs: [
      `03:00. 30.02, then 29.96, then 30.03, inside twenty minutes, on a dead clear windless night with no front for a hundred miles, and I have no honest explanation for it.`,
      `A jump like that wants a cause. A gust front, a distant storm pushing air ahead of it, a thunderhead I could not see. I went out and stood on the lawn at three in the morning like a fool and the sky was full of stars and nothing else.`,
      `The only thing out of the ordinary all night was on the net, not in the sky. Somebody on the boards was up posting about a signal he keeps logging around this hour, timed to the minute, and my little jump landed close to one of his timestamps. I am not saying the two are related. I am a weather man, not whatever he is.`,
      `But I log what I cannot explain, same as the squirrel, same as everything. The jump is in the record at 03:00 on the eighteenth, marked open, cause unknown. If it happens again I will have two points, and two points is the start of a line. Next reading at six, if the needle behaves.`,
    ],
    footnote: `Station 3. Cause unknown. Marked open. See rn:n-carrier-log1 if you are the curious type.`,
    clue: 'timing',
    arc: 'signal',
    related: [{ label: 'The signal he mentioned', url: 'rn:n-carrier-log1' }],
  },
];
