import type { AuthoredPage } from '../types';

/**
 * More drift: the odd corners of an amateur net. Guestbooks, away messages,
 * under-construction pages, webring stops, one page that never rendered right.
 * Short is fine here (drift floor is lower), but every one has a specific voice.
 */
export const DRIFT_EXTRA: AuthoredPage[] = [
  {
    slug: 'drift-guestbook-legend',
    title: "localhost_legend's guestbook",
    author: 'anon',
    hour: 14,
    layout: 'drift',
    tag: 'guestbook',
    updated: '02 Apr 1999',
    search: 'guestbook signatures sign the book visitors',
    drift: true,
    teaser: 'The guestbook itself, a handful of signatures, most of them kind about a page that tries very hard.',
    paragraphs: [
      `> a_friend: cool page. the marquee works now, you did it.`,
      `> soup_judge: signed. the background is a lot but i respect the commitment. 7 out of 10, points for effort.`,
      `> a_friend: signed again, hi, its me from before.`,
      `> modem_mary: your hit counter went up forty overnight because you kept reloading it. it counts you. logged for your own good.`,
      `> a_subscriber: best viewed at 800x600 is a threat and you know it. still signed though.`,
    ],
    footnote: `42 signatures. Sign the book!!!`,
  },
  {
    slug: 'drift-away-carrier',
    title: 'away message: carrier_wave',
    author: 'carrier_wave',
    hour: 2,
    layout: 'drift',
    tag: 'away message',
    updated: '25 Mar 1999',
    search: 'away message listening signal night carrier',
    drift: true,
    teaser: 'Left up for weeks. It says where he went without quite saying it.',
    paragraphs: [
      `away: listening.`,
      `02:14 tonight, like every night. if you decoded it too, do not post the word. we compare privately.`,
      `back when i understand it, or when i stop needing to. those might be the same night.`,
    ],
    footnote: `Set 25 Mar. Still up.`,
  },
  {
    slug: 'drift-under-construction-2',
    title: 'this page is under construction',
    author: 'anon',
    hour: 17,
    layout: 'drift',
    tag: 'under construction',
    updated: '11 Nov 1998',
    search: 'under construction coming soon shovel road sign',
    drift: true,
    teaser: 'A page that is all promise. The construction sign has outlived the construction.',
    paragraphs: [
      `UNDER CONSTRUCTION. Check back soon!`,
      `Coming: photos, links, a page about my cat, maybe MIDI if i figure out how.`,
      `Last worked on: a while ago. The little animated shovel guy is still digging though, so technically progress.`,
    ],
    footnote: `Best viewed at 800x600. Shovel guy provided by the webring.`,
  },
  {
    slug: 'drift-webring-stop',
    title: 'the valley webring: stop 8',
    author: 'anon',
    hour: 15,
    layout: 'drift',
    tag: 'webring',
    updated: '19 Feb 1999',
    search: 'webring next previous random ring valley sites',
    drift: true,
    teaser: 'A ring stop. Next and previous both work, which on this ring is not guaranteed.',
    paragraphs: [
      `You are on stop 8 of the Petersham Valley webring. This ring connects the homepages of people who live near enough to argue in person.`,
      `[ Prev ] takes you to a weather station. [ Next ] takes you to a page that is nine minutes to load. [ Random ] is a coin toss and the ring master will not fix the dead ones.`,
      `To join, you have to know somebody who is already in, which is either a community or a cartel depending on the day.`,
    ],
    footnote: `Ring master: todd_ring. Do not ask him to remove the dead stops.`,
  },
  {
    slug: 'drift-broken-page',
    title: '[ this page did not render ]',
    author: 'anon',
    hour: 13,
    layout: 'drift',
    tag: 'broken',
    updated: '01 Mar 1999',
    search: 'broken page error render tags table unclosed',
    drift: true,
    teaser: 'One page that never came out right. An unclosed tag ate half of it and nobody ever fixed it.',
    paragraphs: [
      `<TABLE><TR><TD>welcome to my`,
      `something went wrong with the table here and the rest of the page is inside a cell that never closed, so it renders as one long column two characters wide, forever.`,
      `the owner knows. the owner has known since March. the owner has decided this is who they are now.`,
    ],
    footnote: `<!-- TODO close the table -->`,
  },
  {
    slug: 'drift-away-angel',
    title: 'away message: xerox_angel',
    author: 'xerox_angel',
    hour: 8,
    layout: 'drift',
    tag: 'away message',
    updated: '12 Mar 1999',
    search: 'away message archive gone index sorry',
    drift: true,
    teaser: 'Short, careful, and it apologises for its own length in three lines.',
    paragraphs: [
      `away: I am not really here anymore, and I am sorry for that, and I am sorry this message is longer than an away message should be.`,
      `The index is still up if you want to understand what I was keeping. Some of it I saved. Some of it I did not get to, and that is the part I think about.`,
      `Please do not sign anything on my behalf. - c`,
    ],
    footnote: `Set 12 Mar. Not taken down.`,
  },
  {
    slug: 'drift-hit-counter',
    title: 'you are visitor number',
    author: 'localhost_legend',
    hour: 16,
    layout: 'drift',
    tag: 'hit counter',
    updated: '03 Apr 1999',
    search: 'hit counter visitor number odometer famous',
    drift: true,
    teaser: 'A hit counter and a boy who checks it more than anyone else does.',
    paragraphs: [
      `YOU ARE VISITOR NUMBER 000439!!!`,
      `The counter is one of those odometer ones with the little rolling numbers and it took me Two Whole Days to get it working and it is the best thing on the page.`,
      `i know some of the visits are me. i do not care. every single one of them Counts and that includes me, i am a visitor to my own page, that is allowed, i checked.`,
    ],
    footnote: `Powered by the free counter from the webring. Do not reload to run it up. (i reload to run it up.)`,
  },
  {
    slug: 'drift-links-page',
    title: 'my links page',
    author: 'localhost_legend',
    hour: 18,
    layout: 'drift',
    tag: 'links',
    updated: '28 Mar 1999',
    search: 'links page cool sites list favorites out',
    drift: true,
    teaser: 'A hand-kept links page, which is how the net worked before anyone searched it.',
    paragraphs: [
      `COOL LINKS!!! (i check these myself so they Actually Work, mostly)`,
      `- the soup board, its about food but its Really about the guy who runs it`,
      `- the weather guy, he was Right about the storm and he will tell you`,
      `- the shelf, get LOGSORT its good even though i dont know what i sort`,
      `- a page that is nine minutes to load, do NOT click this unless you have nine minutes`,
    ],
    footnote: `If your site is not here i probably just havent found it, email me!!!`,
  },
  {
    slug: 'drift-soup-recipe',
    title: 'chowder, the amounts left out',
    author: 'soup_judge',
    hour: 19,
    layout: 'drift',
    tag: 'recipe',
    updated: '22 Feb 1999',
    search: 'chowder recipe salt pork amounts guess soup',
    drift: true,
    teaser: 'A recipe in the only form he knows how to give one, which is badly.',
    paragraphs: [
      `chowder. salt pork not bacon, we have been over this, i will not relitigate it in a recipe.`,
      `you need potatoes, some, and onion, less than you think, and the pork, and milk not cream unless its a sunday. amounts are a trap. cook it till it looks like chowder. you will know.`,
      `the secret is you make it the day before and let it sit, which is not a secret, its just patience, which nobody has, which is why nobody's chowder is as good as it should be.`,
    ],
    footnote: `rated 9 out of 10 by me. the scale is not consistent and neither is the recipe.`,
  },
  {
    slug: 'drift-office-notice',
    title: 'NOTICE: the good scissors',
    author: 'fax_aurora',
    hour: 10,
    layout: 'drift',
    tag: 'memo',
    updated: '16 Mar 1999',
    search: 'scissors missing office notice memo return',
    drift: true,
    teaser: 'The office has escalated the matter of the scissors to the level of a scanned memo.',
    paragraphs: [
      `NOTICE. IT HAS BEEN OBSERVED THAT THE GOOD SCISSORS ARE MISSING.`,
      `THE SCISSORS WERE LAST SEEN AT THE FRONT DESK. THE SCISSORS ARE NOT AT THE FRONT DESK. NO FURTHER SCISSORS WILL BE PURCHASED UNTIL THE GOOD SCISSORS ARE RETURNED.`,
      `THE OFFICE HAS STOPPED CALLING THEM THE GOOD SCISSORS. THEY ARE NOW SIMPLY THE SCISSORS, WHICH IS A DEMOTION THEY EARNED BY LEAVING.`,
    ],
    footnote: `PAGE 1 OF 1. NO RESPONSE IS REQUESTED.`,
  },
  {
    slug: 'drift-monk-small',
    title: 'Item: a small correction',
    author: 'lint_monk',
    hour: 21,
    layout: 'drift',
    tag: 'correction',
    updated: '30 Mar 1999',
    search: 'correction small pedant its it apostrophe',
    drift: true,
    teaser: 'The corrections desk on a slow night, correcting something almost nobody would notice.',
    paragraphs: [
      `Item 1. On the webring stop 8 page, the phrase "its a coin toss" should read "it's a coin toss", the contraction requiring the apostrophe.`,
      `I am aware this is small. I am aware nobody asked. The original read fine to everyone but me, which is precisely the readership a corrections desk serves.`,
      `Source: the page itself, stop 8, second paragraph. No reply expected. The apostrophe is its own reward, and note that "its" there is correct, being possessive.`,
    ],
    footnote: `Corrections desk. Item filed. Nobody thanked.`,
  },
  {
    slug: 'drift-swap-quickie',
    title: 'SWAP MEET: quick one',
    author: 'swap_meet',
    hour: 12,
    layout: 'drift',
    tag: 'classifieds',
    updated: '05 Apr 1999',
    search: 'quick sale free curb alert swap meet',
    drift: true,
    teaser: 'A one-line ad that becomes three lines because he cannot help himself.',
    paragraphs: [
      `FREE: a monitor, works, heavy, you haul. curb alert basically but the curb is my garage.`,
      `its a good monitor i just have a better one now and two monitors is one more monitor than a person needs, my wife says, and she is right, which i hate.`,
      `first come. bring a friend and a strong back. no lowballers, its free, i dont know what you would even lowball, but i mean it in general.`,
    ],
    footnote: `SWAP MEET. Gone by Friday probably.`,
  },
];
