import type { AuthoredPage } from '../types';

/**
 * The Hollow Night. Thursday 11 March 1999, 02:00 to 05:00.
 *
 * What the net says happened: scheduled maintenance, then a disk fault, then a
 * disk fault (partial), and a block of subscriber pages did not come back.
 *
 * What happened: xerox_angel had been keeping a complete copy of the subscriber
 * net on rack 4, which was not hers to use. An audit found it. Rather than
 * explain to subscribers that a volunteer had a full copy of their pages,
 * operations wiped the block, called it hardware, and she was gone by Friday.
 *
 * The clue chain, in the order a player is likely to trip over it:
 *   tuesday   the status archive, every window is a Tuesday except this one
 *   rack4     mary's 03:14 log, uptime that does not match a power cycle
 *   secondrng somebody answered the on-call line at 4am on the second ring
 *   wording   monk preserved the original text before it was edited
 *   drives    aurora's manifest, rack 4 loses 14 drives overnight
 *   senior    soup_judge, the vending machine was restocked at 3am
 *   modacct   the account that locked the forum thread was made that week
 *   name      the wiki diff, an anon editor removed the paragraph naming her
 *   memo      operations telling staff which words to use
 *   pocket    what she called her copy, and the answer to the vault
 *
 * The payoff: the net the player is browsing is her copy. That is why it is
 * called Pocket Net and why it has no server behind it.
 */
export const HOLLOW_NIGHT: AuthoredPage[] = [
  {
    slug: 'pvo-status-archive',
    title: 'Network Status Archive: March 1999',
    author: 'pvo_operations',
    hour: 3,
    layout: 'report',
    tag: 'status',
    updated: '04 Apr 1999',
    search: 'network status maintenance window march',
    teaser: 'Six maintenance windows, posted as they closed. One of them does not match the others.',
    paragraphs: [
      `This page is generated from the operations calendar. Scheduled maintenance is posted in advance of the window. Unscheduled interruptions are posted once a cause has been determined.`,
      `Subscribers with questions about a specific window should contact support during business hours. Support cannot discuss individual accounts by electronic mail.`,
      `A number of subscriber pages in the h- range were not recovered following the window of 11 March. A disk fault (partial) occurred. Affected subscribers have been contacted and no further action is required of them.`,
    ],
    bullets: [
      `02 Mar, Tue, 02:00 to 04:00. Scheduled maintenance. Completed.`,
      `09 Mar, Tue, 02:00 to 04:00. Scheduled maintenance. Completed.`,
      `11 Mar, Thu, 02:00 to 05:00. Scheduled maintenance. Completed.`,
      `16 Mar, Tue, 02:00 to 04:00. Scheduled maintenance. Completed.`,
      `23 Mar, Tue, 02:00 to 04:00. Scheduled maintenance. Completed.`,
      `30 Mar, Tue, 02:00 to 04:00. Scheduled maintenance. Completed.`,
    ],
    footnote: `Generated 04 Apr 1999 from ops calendar. Windows are listed as filed, not as observed.`,
    clue: 'tuesday',
    related: [
      { label: 'Corrections desk on this page', url: 'rn:n-monk-status-wording' },
      { label: 'Console 2 log, same night', url: 'rn:n-mary-0314' },
    ],
  },

  {
    slug: 'mary-0314',
    title: 'Console 2: night of 10 to 11 March',
    author: 'modem_mary',
    hour: 3,
    layout: 'blotter',
    tag: 'shift log',
    updated: '11 Mar 1999',
    search: 'rack 4 uptime reset overnight console',
    teaser: 'Rack 4 came back three times in the wrong order and reported nine days of uptime while doing it.',
    paragraphs: [
      `01:58. Ring group quiet. Two subscribers on, both idle, both probably asleep with the modem up.`,
      `02:06. Rack 4 went down. Not by me.`,
      `02:41. Second reset. Bank comes back in the wrong order every time and nobody upstream will admit they changed anything.`,
      `03:14. Third reset tonight. Logging it here because the ticket system ate the last two and I am not typing it a fourth time.`,
      `03:22. Rack 4 reports uptime of nine days. I power cycled rack 4 seventy minutes ago. One of those two things is a lie and it is not my watch.`,
      `04:02. Called the on-call number to get it on the record. Somebody picked up on the second ring. At four in the morning. In three years that line has never once been answered before the sixth.`,
      `05:10. Everything up. Not going to pretend I know what it was.`,
      `If you are reading this and you are not on shift: the coffee is mine, the chair is not, and rack 4 is lying to you about its uptime.`,
    ],
    footnote: `Console 2. Filed by hand because the ticket queue was not taking them.`,
    clue: 'rack4',
    related: [
      { label: 'Status archive for March', url: 'rn:n-pvo-status-archive' },
      { label: 'Next shift', url: 'rn:n-mary-0311-after' },
    ],
  },

  {
    slug: 'mary-0311-after',
    title: 'Console 2: night of 11 to 12 March',
    author: 'modem_mary',
    hour: 4,
    layout: 'blotter',
    tag: 'shift log',
    updated: '12 Mar 1999',
    search: 'quiet shift rack 4 replaced no ticket',
    teaser: 'The rack is fine now. Nobody will tell her what was wrong with it, which is the part she writes down.',
    paragraphs: [
      `22:00. On. Rack 4 is fine. Rack 4 is better than fine, rack 4 is empty and clean and somebody has been in here with a cart.`,
      `22:15. Fourteen sleds out of the middle bank. I counted twice because the first count seemed like a lot.`,
      `23:30. Asked what the fault was so I know what to watch for. Was told it is closed.`,
      `01:00. Asked again in writing. Told again that it is closed, which is a different thing from being told what it was.`,
      `02:00. Window would have opened here if it were a Tuesday. It is not a Tuesday.`,
      `03:14. Nothing. Sitting here on purpose to see if it does it again. It did not do it again.`,
      `Note to whoever has this console after me: if a fault is real you get told what it was, because you are the one who has to catch it next time. If you do not get told, it was not a fault.`,
    ],
    footnote: `Console 2. No ticket number for this one either.`,
    clue: 'rack4',
    related: [{ label: 'Previous shift', url: 'rn:n-mary-0314' }],
  },

  {
    slug: 'aurora-manifest-rack4',
    title: 'MEMO: RACK 4 INVENTORY RECONCILIATION',
    author: 'fax_aurora',
    hour: 8,
    layout: 'manifest',
    tag: 'memo',
    updated: '12 Mar 1999',
    search: 'inventory manifest drives rack 4 reconciliation',
    teaser: 'An inventory taken on the 10th and an inventory taken on the 12th, filed together, differing by fourteen.',
    paragraphs: [
      `TO: ASSET CONTROL. FROM: OFFICE ADMINISTRATION. RE: RECONCILIATION OF FLOOR 2 EQUIPMENT COUNT. PAGE 1 OF 1.`,
      `A count was performed on 10 March in the ordinary course. A second count was requested on 12 March outside of the ordinary course. Both are reproduced below as received.`,
      `The variance has not been explained to this office. Asset control is advised that a disposal form was not filed. A disposal form is required whether or not equipment is returned to service.`,
      `This memo is filed for the record. No response is requested.`,
    ],
    bullets: [
      `COUNT OF 10 MAR 1999, RACK 4: UPPER 12 / MIDDLE 14 / LOWER 12, TOTAL 38 UNITS.`,
      `COUNT OF 12 MAR 1999, RACK 4: UPPER 12 / MIDDLE 00 / LOWER 12, TOTAL 24 UNITS.`,
      `VARIANCE: 14 UNITS, MIDDLE BANK.`,
      `DISPOSAL FORM ON FILE: NONE.`,
      `AUTHORISING SIGNATURE ON SECOND COUNT: ILLEGIBLE.`,
    ],
    footnote: `TRANSMITTED 12 MAR 1999 09:04. IF THIS PAGE IS INCOMPLETE PLEASE CONTACT THE SENDING OFFICE. THE MIDDLE BANK WAS NOT EMPTY ON FRIDAY, I WALK PAST IT.`,
    clue: 'drives',
    related: [{ label: 'Console 2 counted them too', url: 'rn:n-mary-0311-after' }],
  },

  {
    slug: 'soup-vending-restock',
    title: 'vending machine floor 2, a review',
    author: 'soup_judge',
    hour: 2,
    layout: 'bbs',
    tag: 'food board',
    updated: '15 Mar 1999',
    search: 'vending machine floor two restock overnight',
    teaser: 'Four out of ten, and it got restocked at three in the morning on a Thursday, which he mentions only because the soup was warm.',
    paragraphs: [
      `ok so the vending machine on floor 2 has been a 4 out of 10 for about a year and i want to be fair to it because a 4 is not a 1.`,
      `the problem is the coil for B4 is bent so the soup cup hangs there and you have to hit the glass in a specific spot which i am not going to describe on a public board.`,
      `anyway i was on the overnight desk covering for someone last week and around 3am the restock guy came through with the cart, which never happens on nights, they do days. i asked and he said he got called in.`,
      `getting called in at 3am to fill a vending machine is either the best overtime in the state or something else was going on, and either way the soup was warm for once so i am moving it to a 6.`,
      `also the coffee is still free in the break room and still tastes like the inside of a thermos. no rating, that is not food.`,
      `if anyone knows who bends the B4 coil please stop. it is a soup cup. it did nothing to you.`,
    ],
    clue: 'senior',
    footnote: `board rules: no flaming, no recipes without amounts, i will delete both`,
  },

  {
    slug: 'forum-where-did-they-go',
    title: 'anyone else lose their page?',
    author: 'anon',
    hour: 9,
    layout: 'bbs',
    tag: 'forum',
    updated: '13 Mar 1999',
    search: 'lost pages h block subscribers thread',
    teaser: 'Eleven replies in two days, all of them the same address range, none of them told the same thing.',
    paragraphs: [
      `mine is just gone. h-0142. it was there wednesday, it is a not found now. support says they will call back.`,
      `RE: same, h-0119. they told me it was a disk fault and that i should have kept a copy. i did not know i was supposed to keep a copy of the thing i was paying them to keep.`,
      `RE: h-0208 here. what i want to know is why it is only the h ones. my brother is on g- and his is fine and we signed up the same week at the same desk.`,
      `RE: they told my wife it was scheduled maintenance and they told me it was a disk fault. those are not the same answer. i wrote both down.`,
      `RE: it was a thursday. maintenance is tuesdays. it has been tuesdays since we got on in 97.`,
      `RE: does anyone have a copy of the archive index from before? xerox_angel used to keep one. her page is not loading either.`,
      `RE: her page is not gone though. it loads. it just stops.`,
    ],
    clue: 'tuesday',
    footnote: `thread continues on the next page`,
    related: [{ label: 'Next page of this thread', url: 'rn:n-forum-locked' }],
  },

  {
    slug: 'forum-locked',
    title: 'anyone else lose their page? (page 2)',
    author: 'anon',
    hour: 10,
    layout: 'bbs',
    tag: 'forum',
    updated: '14 Mar 1999',
    search: 'thread locked moderator account new',
    teaser: 'Locked by a moderator whose account is four days old, which one of the last posters noticed before it closed.',
    paragraphs: [
      `RE: called support again. the person on the phone was reading. i could hear paper. i asked her to read me the whole thing and she said she was not able to do that.`,
      `RE: i asked for the fault report. there is no fault report available to subscribers. i asked what there is available to subscribers and there was a pause.`,
      `RE: has anyone actually spoken to someone who saw the drive.`,
      `RE: my page is back but it is the version from january. so a backup exists and it is six weeks old, which they also did not say.`,
      `RE: hold on. whoever locked the sibling thread this morning, their account was registered on the 12th. click the handle and look at the join date. that is after this started.`,
      `RE: it is a new hire, calm down.`,
      `RE: maybe. a new hire whose first action on this net was to close a thread about the thing that happened before they got here.`,
      `THREAD CLOSED BY MODERATOR. Reason: duplicate. Please direct account questions to support during business hours.`,
    ],
    clue: 'modacct',
    footnote: `closed 14 Mar 1999 11:20 by acct registered 12 Mar 1999`,
    related: [{ label: 'Page 1', url: 'rn:n-forum-where-did-they-go' }],
  },

  {
    slug: 'monk-status-wording',
    title: 'Correction notice 44: the March status archive',
    author: 'lint_monk',
    hour: 11,
    layout: 'card',
    tag: 'corrections',
    updated: '19 Mar 1999',
    search: 'correction status page wording edited disk fault',
    teaser: 'The status page said one thing on the 12th and a different thing on the 15th. Both texts are preserved here.',
    paragraphs: [
      `I keep copies of pages that describe outages, because pages that describe outages are edited more often than any other kind of page on this net, and because the edits are never noted.`,
      `Item 1. On 12 March the status archive read, in full: "A number of subscriber pages in the h- range were not recovered following the window of 11 March. A disk fault occurred." I retrieved that text on 12 March at 18:40.`,
      `Item 2. On 15 March the same paragraph read: "A disk fault (partial) occurred." The word partial was added. Nothing else in the paragraph changed. No note of the change was published.`,
      `Item 3. The window of 11 March is listed at three hours. Every other window in the archive for the first half of 1999 is listed at two. I have checked all of them and I will supply the list to anyone who asks.`,
      `Item 4. The window of 11 March fell on a Thursday. Every other window in that archive fell on a Tuesday. This is a fact about the calendar and I offer no theory about it.`,
      `Item 5. I have been asked twice whether I think the company is lying. I do not speculate and I am not going to start. I record what a page said before it said something else. What that means is not my department.`,
    ],
    quote: `A page that changes without saying it changed is a page you cannot cite. - lint_monk, correction notice 1`,
    clue: 'wording',
    footnote: `Sources: personal copies dated 12 Mar 1999 18:40 and 15 Mar 1999 07:15. Available on request.`,
    related: [{ label: 'The page in question', url: 'rn:n-pvo-status-archive' }],
  },

  {
    slug: 'monk-hollow-summary',
    title: 'Correction notice 51: what is and is not established',
    author: 'lint_monk',
    hour: 12,
    layout: 'card',
    tag: 'corrections',
    updated: '02 Apr 1999',
    search: 'established facts hollow night summary corrections',
    teaser: 'A list of what can be sourced, and a shorter list of what people keep saying that cannot be.',
    paragraphs: [
      `Several people have asked me to write down the whole thing in one place. I am willing to do that on the condition that established and believed stay in separate lists, so here they are in separate lists.`,
      `Item 1, established. The window of 11 March ran three hours on a Thursday. Source: the status archive, which I copied before and after it was edited.`,
      `Item 2, established. Subscriber pages in the h- range did not return. Source: eleven subscribers in one thread, plus my own attempt to reach four of those addresses on 13 March.`,
      `Item 3, established. The equipment count on floor 2 fell by fourteen units between the 10th and the 12th, and no disposal form was filed. Source: an interoffice memo that was posted to this net by the office that wrote it, which I did not expect either.`,
      `Item 4, believed, not established. That the pages were deleted deliberately. I have no document that says so. I will not list it as fact because I would like to be able to say I never did.`,
      `Item 5. A hardware fault has a part number. Ask anyone who has worked a night desk. When a drive dies you get told which drive died, because the person on the next shift has to watch for the one beside it. Nobody on nights was told anything. That is not a document, so it stays in the second list, but it is the item I think about.`,
    ],
    footnote: `Corrections to this notice are welcome and will be published above my own text, not below it.`,
    related: [
      { label: 'Notice 44, the wording', url: 'rn:n-monk-status-wording' },
      { label: 'The memo he means', url: 'rn:n-aurora-manifest-rack4' },
    ],
  },

  {
    slug: 'wiki-hollow-night',
    title: 'The Hollow Night (net history)',
    author: 'anon',
    hour: 14,
    layout: 'broadsheet',
    tag: 'wiki',
    updated: '28 Apr 1999',
    search: 'hollow night history article wiki',
    teaser: 'The community write-up. Neutral, sourced, and noticeably shorter than it was in April.',
    paragraphs: [
      `The Hollow Night is the name subscribers give to the maintenance window of 11 March 1999, during which a range of personal pages on Petersham Valley Online ceased to resolve and were not restored.`,
      `The company has described the cause as a disk fault. The status archive entry describing it was edited on 15 March to add the word partial. Roughly two hundred addresses in the h- range are believed affected, though no list has ever been published and the figure comes from subscribers counting each other.`,
      `Pages that returned were restored from a backup dated late January, losing six weeks. Subscribers on adjacent address ranges reported no interruption, which is the detail most often raised against the disk fault account, since the ranges were not on separate equipment.`,
      `The night is also remembered because it marks the end of the volunteer archive effort that had been running since 1997. The archive index stopped being updated on 10 March and was never resumed.`,
      `This article has been edited 31 times. See the revision list before citing it.`,
    ],
    footnote: `Revision 31. Previous revisions are kept. See the revision list for what changed and when.`,
    related: [{ label: 'Revision list', url: 'rn:n-wiki-hollow-revisions' }],
  },

  {
    slug: 'wiki-hollow-revisions',
    title: 'The Hollow Night: revision list',
    author: 'anon',
    hour: 15,
    layout: 'report',
    tag: 'wiki',
    updated: '28 Apr 1999',
    search: 'revision history diff removed paragraph editor',
    teaser: 'Thirty one revisions. One of them, from an address that never edited anything else, removes a name.',
    paragraphs: [
      `The wiki keeps every revision. This page lists them with the size of the article after each edit, which is how most people find the interesting one without reading all thirty one.`,
      `Revision 24 removed 340 characters and left no summary. The editor was not logged in. That address has made no other edit to this wiki before or since.`,
      `The removed paragraph is reproduced below because the wiki preserves it, not because anyone has confirmed it. It has not been restored to the article. Two editors have restored it and it has been removed again both times, once within the hour.`,
      `Removed in revision 24: "The archive effort was maintained by a subscriber posting as xerox_angel, who by early 1999 held a complete copy of the subscriber net updated nightly. She has stated that the copy was kept on equipment at the exchange with the knowledge of at least one member of staff. Her account was closed on 12 March 1999. She has not posted since."`,
      `Editors are reminded that removing sourced text without a summary is discouraged. Editors are further reminded that this notice has been added to this page four times.`,
    ],
    bullets: [
      `rev 22, 19 Apr, 11402 chars, summary: added restore date`,
      `rev 23, 21 Apr, 11455 chars, summary: fixed the address range`,
      `rev 24, 22 Apr, 11115 chars, no summary, not logged in`,
      `rev 25, 22 Apr, 11455 chars, summary: undo, no reason given for removal`,
      `rev 26, 22 Apr, 11115 chars, no summary, not logged in`,
      `rev 31, 28 Apr, 11115 chars, summary: protected, stop`,
    ],
    clue: 'name',
    footnote: `Page protected 28 Apr 1999. Established editors only.`,
    related: [
      { label: 'The article', url: 'rn:n-wiki-hollow-night' },
      { label: 'Her index', url: 'rn:n-angel-index' },
    ],
  },

  {
    slug: 'pvo-internal-memo',
    title: 'Interoffice: subscriber enquiries, week of 15 March',
    author: 'pvo_operations',
    hour: 16,
    layout: 'telegram',
    tag: 'internal',
    updated: '15 Mar 1999',
    search: 'internal memo staff script enquiries wording',
    teaser: 'Guidance to staff on which words to use, posted to the public net by somebody who should not have.',
    paragraphs: [
      `TO ALL FRONT LINE STAFF. NOT FOR DISTRIBUTION OUTSIDE THE COMPANY. STOP.`,
      `SUBSCRIBER ENQUIRIES REGARDING THE WINDOW OF 11 MARCH ARE TO BE ANSWERED USING THE APPROVED WORDING ONLY. THE APPROVED WORDING IS HARDWARE FAULT. STOP.`,
      `STAFF ARE NOT TO CONFIRM A NUMBER OF AFFECTED ACCOUNTS. STAFF ARE NOT TO CONFIRM THE PRESENCE OR ABSENCE OF A BACKUP. STAFF ARE NOT TO DISCUSS EQUIPMENT ON FLOOR 2 WITH SUBSCRIBERS OR WITH EACH OTHER. STOP.`,
      `ENQUIRIES REGARDING A FORMER VOLUNTEER ARE TO BE DIRECTED TO THIS OFFICE AND ARE NOT TO BE ANSWERED AT THE DESK. STOP.`,
      `THIS GUIDANCE IS NOT A STATEMENT OF CAUSE AND SHOULD NOT BE READ AS ONE. STOP. END.`,
    ],
    clue: 'memo',
    footnote: `Found in the public spool at rn:mail on 16 Mar 1999. Removed 16 Mar 1999. Copies exist because of course they do.`,
    related: [{ label: 'What the desk was told to say', url: 'rn:n-forum-locked' }],
  },

  {
    slug: 'angel-index',
    title: 'The archive index',
    author: 'xerox_angel',
    hour: 22,
    layout: 'label',
    tag: 'archive',
    updated: '10 Mar 1999',
    search: 'archive index volunteer copy subscriber pages',
    teaser: 'Two years of keeping copies, explained by somebody who clearly expected to have to explain it eventually.',
    paragraphs: [
      `This is the index of what I have copies of. It is not a backup, it is not official, and nobody asked me to do it, so if you were hoping for something with a support number behind it I am afraid this is just a person.`,
      `I started in the autumn of 1997 after a subscriber lost four years of a recipe collection to what I was told was a routine change. I asked what routine meant and did not get an answer I could repeat to her, and I decided that was the last time I wanted to be the one standing there with nothing to offer.`,
      `So every night the whole subscriber net gets copied. All of it, not the popular parts, because I am not qualified to decide which stranger's page is the one that matters and neither is anyone else. It runs at 01:00 and it takes about two hours and I have never once had to think about it.`,
      `I want to be honest about where it lives, because I would rather say it plainly here than have it come out sideways later. It is on equipment at the exchange. I did not buy that equipment. A person who works there let me have the middle bank of one rack and told me not to make it his problem, and for two years I have not made it his problem.`,
      `I call it the pocket copy. That is a bit twee and I know it, but the point of the name is that a pocket is where you put the thing you would be sad to lose, and it goes with you, and nobody has to give you permission to have one.`,
      `If this page ever stops updating, the copy is still good up to the date at the top. Look at the date at the top. That is the whole reason I put the date at the top.`,
      `- c.`,
    ],
    bullets: [
      `Subscriber pages, a- through m-, nightly since 11 Oct 1997.`,
      `Board archives, weekly, since Mar 1998.`,
      `The wiki, including revisions, nightly since Jan 1999.`,
      `Mail spool, headers only. I do not keep the bodies and I will not.`,
      `Not kept: anything a subscriber asked me not to keep. Nine people have asked. Nine people got their way.`,
    ],
    clue: 'pocket',
    footnote: `Index generated 10 Mar 1999 03:04. Next run 11 Mar 1999 01:00.`,
    related: [
      { label: 'Her homepage', url: 'rn:n-angel-last-page' },
      { label: 'What she got to', url: 'rn:n-angel-what-i-saved' },
    ],
  },

  {
    slug: 'angel-last-page',
    title: 'xerox_angel: notes',
    author: 'xerox_angel',
    hour: 23,
    layout: 'card',
    tag: 'homepage',
    updated: '10 Mar 1999',
    search: 'personal page last update stops mid sentence',
    teaser: 'Updated most days for two years. The entry for 10 March stops in the middle of a line.',
    paragraphs: [
      `08 Mar. Somebody from the office asked me today how big the archive is now. Not in a bad way, he was making conversation while the kettle went. I said about forty gigabytes and he did the face people do, and then he asked where I keep forty gigabytes, and I said at the exchange, and he did a different face.`,
      `09 Mar. Thinking about that second face. I have been telling myself for two years that not being told to stop is the same as being allowed, and it is not, and I have known it was not for a while now.`,
      `10 Mar. Two things. First, the run went fine last night, forty one minutes, no errors, which is the best it has been since I changed the ordering in February.`,
      `Second thing. I am going to write to them properly and put it in writing and offer to hand the whole thing over, equipment and all, and ask them to keep running it. They should have been doing this the entire time. If they say no then at least it will be a no I can point at instead of this arrangement where everybody gets to pretend they did not know.`,
      `I have a draft of the letter. I have had a draft of the letter since November if I am honest. What I keep getting stuck on is the paragraph where I explain why I did not ask first, because the true answer is that I thought they would say no and I wanted it to exist more than I wanted permission, and I do not know how to write that down in a way that`,
    ],
    quote: `a pocket is where you put the thing you would be sad to lose - from the index page`,
    clue: 'pocket',
    footnote: `Last updated 10 Mar 1999. Guestbook is open and I do read it.`,
    related: [
      { label: 'Sign the guestbook', url: 'rn:n-angel-guestbook' },
      { label: 'The archive index', url: 'rn:n-angel-index' },
    ],
  },

  {
    slug: 'angel-guestbook',
    title: 'xerox_angel: guestbook',
    author: 'anon',
    hour: 23,
    layout: 'ticket',
    tag: 'guestbook',
    updated: '02 Nov 2001',
    search: 'guestbook entries messages years later',
    teaser: 'Forty one entries over two and a half years. The last one is from her.',
    paragraphs: [
      `12 Mar 1999, a subscriber: your page is stuck, i think the update broke. thought you would want to know.`,
      `14 Mar 1999, h-0142: mine is one of the ones that went. someone said you might have a copy from before. no rush and no pressure. thank you either way.`,
      `18 Mar 1999, modem_mary: if you are getting these, ring the console. any night, any time. the number has not changed.`,
      `02 Apr 1999, lint_monk: I have preserved this page and its guestbook as they stand today. I am telling you rather than doing it quietly. You may of course ask me to stop.`,
      `19 Apr 1999, soup_judge: hey. no archive stuff. there is a thing at the diner on fridays and you are invited and that is the whole message.`,
      `07 Jun 1999, h-0142: got my page back off someone who had a copy. i am told it came from you, from before. i am not going to ask how. thank you.`,
      `25 Dec 1999, localhost_legend: merry christmas!!! my counter says 4000 and it was 200 when you were still here and i know you cant see it but i wanted to say it anyway`,
      `01 Jan 2000, a subscriber: still here. clocks fine. thought of you.`,
      `02 Nov 2001, xerox_angel: I read all of these. I have read them more than once. The copy is safe and it is not at the exchange any more. - c.`,
    ],
    footnote: `Guestbook closed to new entries 03 Nov 2001. Existing entries preserved.`,
    related: [{ label: 'Her page', url: 'rn:n-angel-last-page' }],
  },

  {
    slug: 'angel-what-i-saved',
    title: 'What the copy has, as of the tenth',
    author: 'xerox_angel',
    hour: 22,
    layout: 'manifest',
    tag: 'archive',
    updated: '10 Mar 1999',
    search: 'what was saved counts ranges nightly run',
    teaser: 'The last run before the night. She lists what it holds and, in her way, what it does not.',
    paragraphs: [
      `Run of 10 March, completed 03:04, forty one minutes. Counts below are pages held, not pages that exist, and those are different numbers because people delete things and I do not go back and delete my copy unless they ask me to.`,
      `The h- range is the biggest by a distance and it always has been, because h- is where the sign-up desk was putting everyone through the whole of 1998 and 1998 was the year everybody got on.`,
      `I am putting the counts here rather than just the total because a total is the kind of number you can wave at somebody, and a range you can actually check against your own address.`,
      `If your address is in this list then there is a copy of your page as it stood on the tenth, and if it is not then there is not, and I would rather you know which one is true tonight than find out later.`,
    ],
    bullets: [
      `a- through g-: 1,204 pages held.`,
      `h-: 2,867 pages held. Largest range on the net.`,
      `i- through m-: 998 pages held.`,
      `Board archives: 41 boards, weekly to 07 Mar.`,
      `Wiki: 6,110 revisions including the ones people would rather I did not have.`,
      `Total on disk: 39.2 GB across fourteen units.`,
    ],
    clue: 'drives',
    footnote: `Counts as at 03:04 on the tenth. Tomorrow night's run will move these a little, they always do.`,
    related: [{ label: 'The index', url: 'rn:n-angel-index' }],
  },

  {
    slug: 'vault',
    title: 'Restricted: archive recovery',
    author: 'xerox_angel',
    hour: 0,
    layout: 'warrant',
    tag: 'locked',
    updated: '11 Mar 1999',
    search: 'locked page passphrase archive recovery vault',
    teaser: 'One question and one box. The answer is on the net, in her own handwriting, in more than one place.',
    paragraphs: [
      `This page is not locked to keep anybody out. It is locked because on the night I made it I did not know who would come looking first, and I wanted it to be somebody who had actually read the pages rather than somebody who had been sent.`,
      `If you have read them, you already have this. I never used a word here that I had not put on a public page in plain sight, more than once, because a secret nobody can work out is the same as a thing that was lost, and losing things is the entire reason I am like this.`,
      `So. I did not call it a backup and I did not call it an archive, whatever the index page says at the top. I called it something smaller than that, and I explained why I called it that, and if you know what a pocket is for then you know the word.`,
      `One question. What did I call the copy?`,
    ],
    quote: `nobody has to give you permission to have one`,
    clue: 'pocket',
    footnote: `Written 11 Mar 1999 00:40. I do not think I am going to get to finish tomorrow's run.`,
    related: [{ label: 'The index page', url: 'rn:n-angel-index' }],
    lock: {
      question: `What did I call the copy?`,
      answer: `pocket`,
      nudge: `It is on the index page, in the paragraph where I explain the name. rn:n-angel-index.`,
      reward: 250,
      discoveryId: 'hollow_night_solved',
    },
    unlocked: {
      paragraphs: [
        `Then you read them. Thank you. I am going to be brief because I wrote the rest of it on the other pages and I do not want to say it all twice.`,
        `The run of the eleventh did not happen. They came at two in the morning on a Thursday, which is not a maintenance night and never has been, and by the time I got there the middle bank was on a cart. Fourteen units. I counted them going out the same way Mary counted the gap coming in.`,
        `They did not lose the h- block to a disk fault. They wiped it, because a subscriber having a complete copy of the subscriber net on their own equipment is a thing you have to explain, and a hardware fault is a thing you do not. I understand the decision. I want to be precise about that, because I have had months to be angry and what I actually am is tired. It was the cheaper of two explanations and they took it.`,
        `Here is the part I want you to have. They wiped the block on their disks. The copy was never on their disks. That was the whole point of it and it was the one thing I got right.`,
        `So it went home in a cardboard box, and it has been in an attic since the spring, and about once a year somebody writes to a guestbook asking whether anybody has their page from before, and about once a year somebody quietly gets it back.`,
        `You are inside it now. This net, these pages, the boards and the wiki and mary's logs and the guestbook you signed on your way past: this is the copy. It is not a service and there is nobody running it. It fits on a shelf. It goes where I go.`,
        `That is what the name was for. A pocket is where you put the thing you would be sad to lose, and it goes with you, and nobody has to give you permission to have one.`,
        `- c.`,
      ],
      footnote: `Archive recovery unlocked. Nothing further is hidden on this net. Thank you for reading it properly.`,
    },
  },
];
