import type { AuthoredPage } from '../types';

/**
 * The rest of the net: the pages that belong to nobody in particular.
 *
 * A net made only of its main characters reads like a cast list. These are the
 * strangers, the one-post accounts, the page somebody made for one thing and
 * never touched again. Most of them have nothing to do with March.
 */
export const TEXTURE_PAGES: AuthoredPage[] = [
  {
    slug: 'lighthouse-index',
    title: 'Lighthouses of the Commonwealth',
    author: 'anon',
    hour: 15,
    layout: 'card',
    tag: 'homepage',
    updated: '02 Mar 1999',
    search: 'lighthouse index sixty one photographs commonwealth',
    teaser: 'Sixty one lighthouses, photographed from the road over four years. The most linked page on the net.',
    paragraphs: [
      `There are sixty one lighthouses in the commonwealth that you can reach without a boat. This page has all of them. It took four years and about nine hundred miles and one speeding ticket I am not going to discuss.`,
      `Every photograph on this site was taken from public land. I want to be clear about that because I get letters. If a light is on a private road then there is no page for it, there is just an entry saying so, and I would rather have a gap than a photograph I had to trespass for.`,
      `My grandfather kept Race Point for eleven years before it was automated in 1972. I did not know him. My mother says he was not a talker, which given he spent eleven years alone in a tower with a light seems like the sort of thing that gets decided for you.`,
      `I started this to see the one he kept and then I could not think of a reason to stop at one.`,
      `Fair warning: the photographs are large and this site is slow. I did try making them smaller. They looked like nothing. A lighthouse at that size is just a white rectangle with weather behind it, and the weather is most of the point.`,
    ],
    bullets: [
      `61 lights reachable by road. 58 photographed. 3 on private roads, listed but not shown.`,
      `Automated: 54. Still crewed: 0. The last one went in 1990.`,
      `Slowest page on this site: number 34, Race Point, at 148 KB.`,
      `Best in fog: number 12. Worst in fog: all of the others.`,
    ],
    footnote: `Last updated 02 Mar 1999. Ring member 15. Best viewed at 800x600.`,
    related: [{ label: 'Number 34', url: 'rn:n-drift-caption' }],
  },

  {
    slug: 'forum-the-splitter',
    title: 'they fixed the B side',
    author: 'anon',
    hour: 6,
    layout: 'bbs',
    tag: 'forum',
    updated: '19 Aug 1999',
    search: 'b side fixed splitter drops stopped thread',
    teaser: 'Ten weeks after the part went in, somebody finally posts the thread confirming it.',
    paragraphs: [
      `Right, it has been ten weeks so I am calling it. The drops have stopped. Nine of us on this thread were on the B side and none of us have had one since June.`,
      `RE: confirmed here too. I had two or three a night for most of a year and I have had none since the start of summer. I bought two modems over that. Two.`,
      `RE: it was a splitter apparently. one part. a year of this and it was one part that somebody could have found in ten minutes if they had been asked to look.`,
      `RE: they were asked to look, repeatedly, by the person on nights. what changed is not that somebody asked, it is that somebody finally asked her and she had four hundred lines of log to hand them.`,
      `RE: is she still there? i rang the console in july about something else and it was a bloke.`,
      `RE: she left at the end of april. so she logged it for four months, left, and the fix landed in june off the back of the log she kept.`,
      `RE: that is either quite sad or quite good and i genuinely cannot decide which.`,
      `RE: bit of both probably. anyway. buy fewer modems, everyone.`,
    ],
    footnote: `Thread archived by the board. 31 replies, 9 confirmations.`,
    related: [{ label: 'The log they mean', url: 'rn:n-mary-ring-group-b' }],
  },

  {
    slug: 'guestbook-lighthouse',
    title: 'Lighthouses: guestbook',
    author: 'anon',
    hour: 12,
    layout: 'ticket',
    tag: 'guestbook',
    updated: '14 Nov 1999',
    search: 'guestbook lighthouse entries visitors messages',
    teaser: 'Signatures from people who waited nine minutes for a photograph and thought it was worth saying so.',
    paragraphs: [
      `08 Nov 1998, a visitor: number 41 is my grandmother's light. I have not seen it since I was a child and I did not expect to see it tonight. Thank you.`,
      `19 Dec 1998, localhost_legend: this took NINE MINUTES to load and i sat and watched the whole thing come down the screen and honestly that was kind of the best part???`,
      `03 Feb 1999, lint_monk: Your date for the Race Point automation is correct and mine was not. I have published a correction against myself. No reply needed.`,
      `28 Feb 1999, a visitor: drove out to number 12 on the strength of this page. It was foggy. Could not see the light at all. Ten out of ten, would fail to see it again.`,
      `11 Jul 1999, a visitor: is this site coming back? it has been not loading since march and i keep checking.`,
      `02 Sep 1999, a visitor: still checking.`,
      `14 Nov 1999, a visitor: somebody sent me the whole site on three floppies. all sixty one. i do not know who and the note just said you were looking for this. i have printed number 41 and it is on the wall.`,
    ],
    footnote: `Guestbook remains open. The site does not. Both of those facts are on purpose now.`,
    related: [{ label: 'The site itself', url: 'rn:n-lighthouse-index' }],
  },

  {
    slug: 'the-shortbread-tin',
    title: 'THE TIN (rules for)',
    author: 'anon',
    hour: 9,
    layout: 'label',
    tag: 'notice',
    updated: '18 Nov 1999',
    search: 'tin shortbread break room rules anonymous',
    teaser: 'A note taped to a biscuit tin, amended four times by four different hands.',
    paragraphs: [
      `THE TIN. Rules, agreed by nobody, enforced by everybody.`,
      `1. Whoever empties it fills it. Not immediately. When you get round to it. It has never been empty more than four days and nobody has ever been asked.`,
      `2. No names. Not on the tin, not in the tin, not on the boards. If you tell people it was you then it becomes a thing you did, and the whole point is that it is a thing that happens.`,
      `3. Shop bought is fine. This was added in June by somebody who clearly felt got at and they were right to add it.`,
      `4. If it is empty and you cannot bake and you cannot get to a shop, put something else in it. In August it was a bag of apples for a fortnight and that counted.`,
      `5. Added 18 Nov: the tin goes with us to the new floor. This was raised as a question and answered in about nine seconds by everyone at once.`,
    ],
    footnote: `Taped to the lid. Four different pens. Do not tidy this up, somebody tried and it was put back.`,
  },

  {
    slug: 'directory-note',
    title: 'About this directory',
    author: 'anon',
    hour: 17,
    layout: 'report',
    tag: 'directory',
    updated: '20 Dec 1999',
    search: 'directory about listing policy dead sites',
    teaser: 'The listing policy, including the decision about what to do with sites that stop answering.',
    paragraphs: [
      `This directory lists every subscriber site on the net that has been submitted to it. Submission is by mail and there is no approval process beyond checking that the address resolves at the time of listing.`,
      `Sites are grouped by what they are about rather than alphabetically, because alphabetically was tried first and it turns out nobody has ever wanted to browse the letter G.`,
      `Dead sites stay listed. This was argued about at length in the spring and the argument went roughly like this: a directory that removes what is gone is a directory of what is currently convenient, and one that keeps it is a record. Both are useful. Only one of them can be undone later.`,
      `Listings for sites that no longer answer are marked, not hidden. If you follow one and get nothing, that is not a fault in the directory. That is the directory doing the one thing it is for.`,
      `Corrections to any listing are welcome and will be made without argument, which I mention because there is a gentleman on this net who has tested that claim eleven times.`,
    ],
    footnote: `Listings: 240 live, 47 marked as not answering. Last walked 20 Dec 1999.`,
  },

  {
    slug: 'forum-y2k',
    title: 'so what actually happens at midnight',
    author: 'anon',
    hour: 23,
    layout: 'bbs',
    tag: 'forum',
    updated: '28 Dec 1999',
    search: 'y2k midnight rollover january 2000 panic thread',
    teaser: 'Forty replies of escalating certainty, and one from somebody who has actually checked.',
    paragraphs: [
      `Serious question. My brother in law has bought tinned food. Is there anything to this or is he going to be eating tinned peaches until March.`,
      `RE: he is going to be eating peaches until March.`,
      `RE: it is not nothing though. the two digit year thing is real, it is just that it is real in the way a spelling mistake is real, not in the way a fire is real.`,
      `RE: my bank sent a letter saying they are fine. that is either reassuring or the exact thing you would send if you were not fine, and i have been going round in circles on that for a week.`,
      `RE: the night desk here says the exchange gear has been rolled forward and tested twice and the only thing that broke was a printer that put the wrong year on a header. a printer.`,
      `RE: right but a printer here is a printer. somewhere else it is something that matters.`,
      `RE: sure. and somewhere else somebody has also checked it, because this is the most warned about problem in the history of the trade. the reason nothing much is going to happen is that everybody spent four years making sure nothing much would happen, and then everybody is going to say see, nothing happened.`,
      `RE: that is the most depressing description of a job well done i have ever read and i am going to think about it every new year for the rest of my life.`,
    ],
    footnote: `Thread continued to 41 replies. Consensus: peaches.`,
  },

  {
    slug: 'the-new-floor',
    title: 'Moving day',
    author: 'anon',
    hour: 8,
    layout: 'broadsheet',
    tag: 'notice',
    updated: '04 Dec 1999',
    search: 'moving new premises floor exchange relocation',
    teaser: 'The company is moving three streets over, and a list of what is going and what is not.',
    paragraphs: [
      `Petersham Valley Online moves to new premises on the eighteenth. Three streets, one floor up, and about four hundred metres of cable that somebody has to label first.`,
      `Subscribers should notice nothing. The exchange gear moves overnight on the seventeenth in two lifts, with the second lift not starting until the first is answering, which means a slow night rather than a dark one.`,
      `Going: everything in the racks, the console, the wall thermometer that was installed after the August we do not talk about, the tin from the break room, and, after a short discussion that was not really a discussion, a chipped mug.`,
      `Not going: the vending machine on floor 2, which is being left because the new building has its own and because moving it was quoted at more than the machine is worth. Its coil is still bent. A small delegation has asked about this.`,
      `The old building goes back to the landlord in January. Somebody has asked whether the marks by the stair door where the fire door has been propped every day for six years count as damage. This is being looked into.`,
    ],
    footnote: `Notice posted 04 Dec 1999. Move 17 to 18 Dec. Nothing is expected to go wrong, which is what was said in August.`,
  },

  {
    slug: 'chat-log-friday',
    title: 'Relay: Friday night, saved',
    author: 'anon',
    hour: 19,
    layout: 'receipt',
    tag: 'chat',
    updated: '06 Aug 1999',
    search: 'chat log relay saved conversation friday night',
    teaser: 'Somebody hit save on an ordinary Friday in the chat room. Nothing happens in it.',
    paragraphs: [
      `[21:04] someone joined`,
      `[21:04] hello`,
      `[21:07] hi. quiet tonight`,
      `[21:07] it is friday, everyone is at the diner`,
      `[21:08] i am at the diner. i am at the diner on the payphone. this is a joke, i am at home`,
      `[21:14] did the splitter thing actually fix it for you`,
      `[21:15] yeah. nothing since june. i bought two modems for no reason`,
      `[21:15] two!!`,
      `[21:16] two.`,
      `[21:31] going to go, the dog wants out`,
      `[21:31] night`,
      `[21:32] someone left`,
    ],
    footnote: `Saved 06 Aug 1999 by a user who has never explained why they saved this particular one.`,
  },
];
