import type { AuthoredPage } from '../types';

// the signal, second mystery arc. carrier_wave logs a repeating night
// transmission, decodes it over weeks, goes quiet.
// the solve: the signal is the exchange's automated night line test, a carrier
// the linemen nicknamed the lighthouse bc it pulses all night to tell the gear
// the line is still alive. vault answer is `lighthouse`, planted in plain prose
// on carrier-the-tech.
// clue pages elsewhere (arc:'signal') point inward: hank-the-anomaly (timing),
// daemon-nightlog (recorder), swap-the-mystery-box (tapes), aero (future).
export const SIGNAL_PAGES: AuthoredPage[] = [
  {
    slug: 'carrier-log1',
    title: 'Night Watch: log one',
    author: 'carrier_wave',
    hour: 3,
    layout: 'blotter',
    tag: 'watch log',
    updated: '26 Feb 1999',
    search: 'signal night transmission repeating log carrier watch',
    teaser: 'The first night he wrote it down instead of dismissing it. A tone, a run of clicks, and a time that would not change.',
    paragraphs: [
      `02:14 and change. There it is again. I have heard it four nights running and tonight is the night I stopped telling myself it was nothing and started keeping a proper log, so this is log one and every one after it is timed to the second.`,
      `What it is: a low tone, maybe a second long, then a run of clicks, then silence, then it repeats twice more and stops. The whole thing takes under a minute. Then the line is just the line again, hiss and nothing, until the same time tomorrow.`,
      `I am not a crank. I want that on the record at the top, before any of this goes further. I fix radios for a living, I know what a bad connection sounds like, I know what crosstalk sounds like, and this is neither. This is regular. Bad connections are not regular. Regular means somebody, or something, is doing it on purpose.`,
      `So I am going to log it, every night, at the same time, until I understand it. If you are reading this and you have heard it too, and I do not think I am the only one, write it down with a timestamp and compare. Two logs that agree on a time are worth more than either one alone.`,
    ],
    footnote: `Night Watch, log one. 02:14. Timed to the second from here on.`,
    clue: 'signal-heard',
    arc: 'signal',
    related: [{ label: 'The timing, nailed down', url: 'rn:n-carrier-timing' }],
  },

  {
    slug: 'carrier-timing',
    title: 'Night Watch: the clock does not drift',
    author: 'carrier_wave',
    hour: 2,
    layout: 'report',
    tag: 'watch log',
    updated: '02 Mar 1999',
    search: 'signal timing precise clock exact seconds schedule',
    teaser: 'Two weeks of timestamps prove the one thing that matters most: it does not drift. Whatever sends it keeps perfect time.',
    paragraphs: [
      `Fourteen nights of it now and here is the finding that changed how I feel about the whole thing: it does not drift. Not by a second. It arrives at 02:14 and the same number of seconds past, every single night, tighter than my own watch keeps.`,
      `That matters more than anyone I have told seems to get. A person cannot do this. A person forgets, sleeps in, has a night off. A loose wire cannot do it either, because loose wires answer to temperature and weather and this thing ignores both. I logged it through the cold snap and through the thaw and it never moved.`,
      `Only two kinds of thing keep time like that. A very good clock, and a thing driven by a very good clock. Which means whatever sends this is not improvising. It is on a schedule set by a machine that does not tire, and it has been keeping that appointment in the dark every night whether anyone was listening or not.`,
      `I got a weather fellow's attention with this, oddly. He logged an odd jump on his barometer near one of my timestamps and wrote it up. Probably unrelated, two careful men noticing the same clock hour. But I have started collecting the "probably unrelateds," because in my experience a pile of those is sometimes just a pattern nobody has turned the right way up yet.`,
    ],
    footnote: `Night Watch. Zero drift over fourteen nights. That is the whole finding.`,
    clue: 'timing2',
    arc: 'signal',
    related: [{ label: "The weather man's jump", url: 'rn:n-hank-the-anomaly' }],
  },

  {
    slug: 'carrier-recording',
    title: 'Night Watch: getting it on tape',
    author: 'carrier_wave',
    hour: 2,
    layout: 'report',
    tag: 'watch log',
    updated: '09 Mar 1999',
    search: 'recording tape capture signal nightlog tool decode prepare',
    teaser: 'To decode it he first has to catch it cleanly, which means a recorder that does not lie about the time.',
    paragraphs: [
      `You cannot decode what you cannot capture cleanly, and my problem for three weeks was that I was transcribing the clicks by ear at two in the morning, which is exactly the condition under which a tired brain invents the pattern it is hoping to find.`,
      `So I needed it on tape, timed. I asked a sysop who writes small utilities whether he could make me a recorder that timestamps whatever the modem hears and does not round the clock, because a recorder that fudges the timing would poison the one measurement I actually trust. He built it. NIGHTLOG, he calls it, and it does exactly the one thing I asked and nothing else, which is the mark of a good tool and a good man.`,
      `Now I have clean captures, a dozen of them, each with the clicks preserved and the clock honest to the second. I can play them slow. I can play them backward. I can lay two nights side by side and see that the clicks fall in the same places, which by ear I could only suspect and now I can prove.`,
      `A woman on the classifieds turned up with a box of tapes labelled only with times, times like mine, and offered me the numbers off them free. I have not heard those tapes yet. But somebody was recording this before me, and labelled the tapes the way I would, and then let a box of them go in a trade, and I would very much like to know why a person stops.`,
    ],
    footnote: `Night Watch. Clean captures now, clock honest. The tool is at rn:n-daemon-nightlog.`,
    clue: 'capture',
    arc: 'signal',
    related: [{ label: 'The tapes somebody let go', url: 'rn:n-swap-the-mystery-box' }],
  },

  {
    slug: 'carrier-decode-one',
    title: 'Night Watch: the clicks are not random',
    author: 'carrier_wave',
    hour: 3,
    layout: 'report',
    tag: 'decode',
    updated: '13 Mar 1999',
    search: 'decode clicks pattern groups signal analysis morse rhythm',
    teaser: 'Slowed down and laid side by side, the clicks resolve into short groups that repeat. He is careful not to jump.',
    paragraphs: [
      `Progress, and I am going to state it carefully because this is the point where a person like me starts seeing faces in wallpaper. The clicks are not random. Slowed down and lined up across nights, they fall into short groups, and the groups repeat in the same order every time.`,
      `I count the same run each night. A short group, then a longer one, then the short group again, then silence, then the whole thing twice more. It has the rhythm of something being said, not the mush of something breaking. Breaking is arrhythmic. This has meter.`,
      `Now, the trap. Any regular rhythm can be read as a message if you want a message badly enough, and I want one badly, and I know that about myself, so I am refusing to assign meaning to the groups yet. Right now all I will claim is: three groups, fixed order, repeated three times. That is measurement. Meaning comes later or not at all.`,
      `What I keep coming back to is how short it is. Whatever this is saying, it is saying very little, and saying it over and over. That is not how people talk. That is how a marker talks. A thing that repeats the same tiny message all night is not trying to tell you a story. It is trying to tell you it is there.`,
    ],
    footnote: `Night Watch. Three groups, fixed order, thrice nightly. No meanings assigned yet.`,
    clue: 'decode',
    arc: 'signal',
    related: [{ label: 'Where the groups finally broke', url: 'rn:n-carrier-decode-two' }],
  },

  {
    slug: 'carrier-decode-two',
    title: 'Night Watch: it is one word',
    author: 'carrier_wave',
    hour: 4,
    layout: 'report',
    tag: 'decode',
    updated: '17 Mar 1999',
    search: 'decode word repeating signal meaning breakthrough groups letters',
    teaser: 'The three groups resolve to letters, and the letters spell one short word, repeated all night. He will not write the word yet.',
    paragraphs: [
      `I have the groups as letters now, and I am shaking a little as I type this, so forgive the tone. Read against a standard code, the three groups are three syllables, and the three syllables are one word, and it is the same word every night, three times a night, since before I started listening.`,
      `I am not going to write the word on this page. Not out of drama, though I feel the drama, but because I want it confirmed by someone who is not me, someone who did not spend three weeks wanting it to say something. If I print it here, everyone who reads it afterward will hear that word in the clicks whether it is there or not, and I will have ruined the only clean test left.`,
      `What I will say is this. It is not a name. It is not a distress word, nothing frightening, which honestly disappointed the part of me that wanted a rescue to run. It is an ordinary word, a plain object, the kind of thing you would point at. And the moment I read it, the whole feeling of the signal changed, from a message meant for me to something much older and sadder that was never meant for anyone.`,
      `If you have decoded it too, do not post the word. Post that you have it, and post your timestamps, and we will compare privately, because the word deserves to be confirmed and not spread. It has waited every night in the dark to be understood. It can wait a few more for us to get it right.`,
    ],
    footnote: `Night Watch. One word, three syllables, withheld on purpose. Confirm, do not spread.`,
    clue: 'oneword',
    arc: 'signal',
  },

  {
    slug: 'carrier-the-dismissal',
    title: 'Night Watch: I called the exchange',
    author: 'carrier_wave',
    hour: 5,
    layout: 'report',
    tag: 'watch log',
    updated: '19 Mar 1999',
    search: 'phone exchange line test dismissal official explanation carrier',
    teaser: 'The official answer arrives and it is a shrug: a line test, no action required. He does not quite believe the shrug.',
    paragraphs: [
      `I did the sensible thing at last and called the telephone exchange, and I got the sensible answer, and the sensible answer is a shrug, and I am writing down why the shrug did not settle me.`,
      `A man at the exchange, kind, bored, told me it was almost certainly a line test. The equipment sends a test carrier down idle lines overnight to confirm they are still good, he said, and it runs on a clock, and it repeats, and yes it would be dead regular, and no it does not mean anything, and have a good night.`,
      `Which explains everything. The timing, the regularity, the shortness, the fact that it says the same tiny thing over and over. A machine checking that the line is alive would sound exactly like this. I hung up and felt the whole three weeks deflate, and I want to be honest that for an hour I was relieved and disappointed in exactly equal measure.`,
      `But here is the part the man could not answer, because it was not his department, and it is the part I cannot let go. If it is just a test, why does it say a word? A test needs a tone. A test does not need to spell anything. Somebody, at some point, chose to make the test say a specific word, and chose that word, and I want to know who and why, because that choice was not made by a machine. That choice was made by a person, once, a long time ago.`,
    ],
    footnote: `Night Watch. Official answer: line test, no action required. Unanswered: why a word.`,
    clue: 'dismissal',
    arc: 'signal',
    related: [{ label: 'The old lineman who wrote in', url: 'rn:n-carrier-the-tech' }],
  },

  {
    slug: 'carrier-the-tech',
    title: 'Night Watch: a lineman writes in',
    author: 'carrier_wave',
    hour: 4,
    layout: 'bbs',
    tag: 'watch log',
    updated: '22 Mar 1999',
    search: 'retired lineman exchange nickname lighthouse test carrier answer',
    teaser: 'A retired exchange man reads the logs and finally explains the word, and the name the crews gave it.',
    paragraphs: [
      `A retired lineman found these logs and wrote me a long careful message, and it is the answer, and it is better and sadder than anything I had guessed, and with his blessing I am putting the heart of it here.`,
      `He worked the exchange for thirty years. The night test carrier is real, he confirms, and it does spell a word, and the word was not chosen by any machine. In the early days a crew set it up, and rather than send a meaningless tone into the dark all night, one of them programmed it to send a single plain word, over and over, as a small private joke and a kind of company. They picked an object, something steady, something that stands in the dark and pulses so ships know the shore is still there.`,
      `They called it the lighthouse. That was the crew's name for the whole test unit, because that is what it does, all night, forever: it stands there and it pulses, saying the same word to nobody, telling the empty lines that the shore is still there and still holding. The lighthouse. Once you know the word is lighthouse the clicks are unmistakable, three syllables, three times a night, since before any of us were listening.`,
      `He said the crew that built it are mostly gone now, and the joke is forgotten by everyone but the machine, which does not know it is a joke and keeps the appointment anyway, faithful, pointless, kind. I asked why it moved me so much and he said, because you spent three weeks proving that something in the dark was keeping time for no one, and then you found out its name was lighthouse, and of course that moved you. Of course it did.`,
    ],
    quote: `it stands in the dark and pulses so the empty lines know the shore is still there`,
    footnote: `Night Watch. The word is confirmed, and the crew's name for it is confirmed, by a man who was there.`,
    clue: 'thename',
    arc: 'signal',
    related: [{ label: 'The last log', url: 'rn:n-carrier-last' }],
  },

  {
    slug: 'carrier-last',
    title: 'Night Watch: log, final, unfinished',
    author: 'carrier_wave',
    hour: 5,
    layout: 'blotter',
    tag: 'watch log',
    updated: '25 Mar 1999',
    search: 'final log stop watching signal resolved quiet unfinished carrier',
    teaser: 'The last entry. He got his answer and it took the reason to keep listening, and the log stops mid-thought.',
    paragraphs: [
      `Last log, I think, and it is a strange thing to write, because I got exactly what I wanted, which was to understand it, and understanding it has quietly taken away the reason to sit up.`,
      `I still hear it. 02:14, three syllables, three times, the lighthouse keeping its appointment. Now that I know the word I cannot un-know it, and every night it says lighthouse to the empty lines and to me, and the mystery that kept me up is gone and only the sadness is left, and the sadness turns out to be the part I will actually miss.`,
      `The old lineman said something I keep turning over. He said the saddest machines are the faithful ones, the ones that keep doing a kindness after everyone who understood the kindness has gone. That is the whole signal. A joke told to nobody, forever, in perfect time, because the crew that told it never wrote a stop into the code, and who would.`,
      `So I am going to stop logging and just listen for a while, the way you listen to rain. If you decoded it too, you know now why I never printed the word until a man who was there confirmed it. Some answers you have to earn by reading, or they are just trivia. This one you had to sit up three weeks for. I hope it was worth your`,
    ],
    footnote: `Night Watch. Last entry, left as it ended. carrier_wave, March 1999.`,
    clue: 'ending',
    arc: 'signal',
    related: [{ label: 'The recovered decode', url: 'rn:n-carrier-vault' }],
  },

  {
    slug: 'carrier-vault',
    title: 'Night Watch: the sealed decode',
    author: 'carrier_wave',
    hour: 4,
    layout: 'warrant',
    tag: 'decode',
    updated: '24 Mar 1999',
    search: 'sealed decode answer word signal vault lighthouse locked',
    teaser: 'The one page he sealed: the full decode. It opens only for someone who read the logs and knows the word.',
    paragraphs: [
      `This is the page I sealed on purpose. Behind it is the full decode, the letter-by-letter working, the thing I would not print in the open because a word spread is a word ruined, but a word earned is a word kept.`,
      `If you read the logs, and you read the lineman's message, you already have the word. It is a plain object, three syllables, a thing that stands in the dark and pulses so the shore is known. The crew named the whole test unit after it. Type that word and the working opens.`,
      `I am not gatekeeping for cruelty. I am doing it because this answer only means anything if you sat up for it the way I did. Anyone can be told a word. Only someone who followed the timing and the tapes and the decode and the old man's letter has actually understood it, and understanding is the only key I was ever willing to cut.`,
    ],
    lock: {
      question: `What did the linemen call it?`,
      answer: `lighthouse`,
      nudge: `The retired lineman spelled it out in plain words. His message is the page at rn:n-carrier-the-tech.`,
      reward: 250,
      discoveryId: 'signal_solved',
      achievement: { id: 'the_signal', title: 'The Lighthouse' },
      revealToast: 'Night Watch decode recovered',
    },
    unlocked: {
      paragraphs: [
        `Recovered. Here is the full working, the thing I sat on until someone earned it.`,
        `The carrier arrives at 02:14 and eleven seconds, dead regular, and runs the same envelope three times: a long group, a short group, a middle group, then silence, then again, then again. Against a standard code the three groups are three syllables and the three syllables are the word the lineman confirmed. Once you have it you cannot hear anything else.`,
        `I timed it against the exchange's own maintenance window and it lines up to the minute, which is the last proof I needed that the kind bored man on the phone was right about the what, even though he had no idea about the why. It is a test. It is also the crew's small forever joke, and both of those are true at once, and holding both is the whole thing.`,
        `The weather man's barometer jump was a coincidence, I am now sure, two careful people awake at the same dead hour. The tapes in the classified box were an earlier watcher who gave up, and I understand her better now than I did, because I am giving up too, in the good way, the way you close a book you finished.`,
        `If you are reading this, you read the whole net to get here, and that means you are the kind of person the lineman's crew would have liked. They left a kindness running in the dark for no one. You stayed up until you understood it. That is the same gesture pointed in opposite directions, and between the two of you the joke finally landed, decades late, exactly as intended.`,
        `Watch is closed. The lighthouse keeps its appointment tonight and every night, saying its one steady word to the empty lines. Now you know its name too. - cw`,
      ],
      footnote: `Night Watch decode, recovered. Sealed 24 March 1999, opened by you.`,
    },
    arc: 'signal',
  },
];
