import type { AuthoredPage } from '../types';

/**
 * More pages for the founding voices. Same rules as their home files: cover the
 * byline and you should still know who wrote it. One combined file so the wiring
 * is a single import.
 */
export const EXTRA_PAGES: AuthoredPage[] = [
  // --- modem_mary ---
  {
    slug: 'mary-the-cart',
    title: 'Console 2: the three a.m. cart',
    author: 'modem_mary',
    hour: 3,
    layout: 'blotter',
    tag: 'shift log',
    updated: '09 Feb 1999',
    search: 'office cart night three am unusual visitor console',
    teaser: 'She warned her replacement about this in the handover. Here is the night it happened to her.',
    paragraphs: [
      `03:00. Someone came through from the office side with a cart. Three in the morning. Acted like it was the most normal thing in the world, which is exactly the thing I told the next operator to distrust.`,
      `03:05. Asked if they needed anything. Got a no thank you, friendly, and a squeak of wheels going toward the rack room. I logged the time and the direction because logging the time and the direction is the whole job.`,
      `03:40. Cart went back the other way, lighter or heavier I could not tell, and I am not going to pretend I could. What I can tell you is it came, it went, and nobody mentioned it on any day shift after.`,
      `I am not saying it was anything. Nights is full of nothing that looks like something at three in the morning. But the rhythm was off, and when the rhythm is off you write it down, and you trust the writing over anyone who tells you later that you imagined the wheels.`,
    ],
    footnote: `Console 2. Cart at 03:00, gone by 03:40. Logged, unexplained.`,
  },
  {
    slug: 'mary-the-manual',
    title: 'Console 2: the manual with no lamp',
    author: 'modem_mary',
    hour: 4,
    layout: 'blotter',
    tag: 'shift log',
    updated: '26 Feb 1999',
    search: 'manual instructions lamp indicator wrong equipment night',
    teaser: 'A running argument with a manual written by somebody who never sat at the console.',
    paragraphs: [
      `04:00. Read more of the new ring group manual because the night is dead and spite is a renewable resource.`,
      `Whoever wrote this has never worked a night. Page 40 says observe the indicator lamp during a reset. No such lamp exists on this unit and none ever has. I checked with a flashlight to be sure I was not the problem, and I was not, the lamp is simply a fiction of page 40.`,
      `Page 52 tells you to contact the daytime supervisor if the fault persists. The daytime supervisor is asleep, as is correct, because it is four in the morning, which the manual seems not to know is a time that exists.`,
      `A manual written by someone who has never done the job is worse than no manual, because it sounds official while being useless, and a new operator will trust it over their own eyes for exactly one bad night before they learn. I am writing this so they learn it here instead.`,
    ],
    quote: `the lamp is a fiction of page 40`,
    footnote: `Console 2. The manual is wrong on pages 40 and 52. Trust the unit.`,
  },
  {
    slug: 'mary-the-tea',
    title: 'Console 2: on the machine coffee',
    author: 'modem_mary',
    hour: 22,
    layout: 'card',
    tag: 'notes',
    updated: '18 Jan 1999',
    search: 'coffee machine cupboard tea night desk small comforts',
    teaser: 'A short one, about the single most important piece of equipment in the room.',
    paragraphs: [
      `22:00. On. First order of business, as every night, is the coffee, and I have opinions, and this is my page, so.`,
      `The machine in the hall dispenses something it calls coffee. It is not coffee, it is a warning about coffee, a brown liquid that has heard coffee described and is doing its best from memory. Do not drink it.`,
      `The real coffee is in the cupboard, the tin, behind the manual nobody opens. You make it in the pot. It takes four minutes and those four minutes are the difference between a shift and a sentence.`,
      `I am putting this in writing because the single kindest thing one night operator can do for the next is tell them where the real coffee is, and nobody told me, and I found the tin in month three, and I have been quietly furious about those first two months ever since.`,
    ],
    footnote: `Console 2. Cupboard, not machine. You are welcome.`,
  },
  {
    slug: 'mary-last-look',
    title: 'Console 2: what I checked, every night',
    author: 'modem_mary',
    hour: 6,
    layout: 'manifest',
    tag: 'shift log',
    updated: '29 Apr 1999',
    search: 'checklist end of shift routine console handover',
    teaser: 'The end-of-shift routine, written out, so it survives her leaving.',
    paragraphs: [
      `Six in the morning, every morning, the same last look before I hand off. It is a routine and routines are how you catch the thing that only shows up when you are not looking for it.`,
      `The list, so the next operator has it in one place instead of learning it a fright at a time.`,
    ],
    bullets: [
      `Ring group A and B counts logged, even when zero, especially when zero`,
      `Room temperature written down off the wall thermometer, the one we got after August`,
      `Rack 4 uptime noted, because rack 4 has lied before and will lie again`,
      `Any office-side traffic and its time, cart or person, no matter how normal it acted`,
      `Coffee pot rinsed, because leaving it dirty is how the day shift learns to resent nights`,
    ],
    footnote: `Console 2. The last look. Do it even when the night was nothing.`,
  },

  // --- soup_judge ---
  {
    slug: 'soup-vending-two',
    title: 'the floor two vending machine, a review',
    author: 'soup_judge',
    hour: 12,
    layout: 'bbs',
    tag: 'review',
    updated: '11 Feb 1999',
    search: 'vending machine floor two review rating snacks',
    teaser: 'A full and unfair review of a machine that has personally wronged him.',
    paragraphs: [
      `the floor two vending machine gets a 3 out of 10 and honestly thats generous and heres why, buckle up.`,
      `the B4 slot eats your money about one time in five and there is no appeal, no button, no person, just the machine and your loss and the specific silence after. i have written to the office. the office joined a message board to tell us timesheets are due and said nothing about B4.`,
      `it does have the good crackers though, the orange ones, and when it actually vends them its the best thing on the floor, which is the whole tragedy of the machine, its capable of greatness and chooses chaos.`,
      `anyway 3 out of 10, would be a 7 if B4 worked, would be a 2 if not for the orange crackers. the scale is not consistent. i have never claimed it was. bring exact change and low expectations and you will occasionally be delighted.`,
    ],
    footnote: `soup_judge. floor two machine. 3 out of 10. respect the orange crackers.`,
  },
  {
    slug: 'soup-friday-diner',
    title: 'friday, the usual place, an explanation',
    author: 'soup_judge',
    hour: 18,
    layout: 'bbs',
    tag: 'board',
    updated: '05 Mar 1999',
    search: 'friday diner meetup broken sign end seat regulars',
    teaser: 'What the Friday thing actually is, for anyone new who keeps asking.',
    paragraphs: [
      `people keep asking what the friday thing is so ok. the friday thing is some of us go to the diner with the broken sign and eat and do not talk about work. thats it. thats the whole thing.`,
      `there is no agenda. there is no list. four of us last week which is a good number, six is too many, two is a little sad but fine. you do not have to come every week. you do not have to come at all. you are just told, so you know its there.`,
      `the seat at the end stays empty and please do not make it weird by asking why, some of us know why and the rest of us have decided not to need to, and both of those are allowed, and that is sort of the whole spirit of the friday thing actually.`,
      `so thats it. friday, the place with the broken sign, whenever you want, no talking about march. you can talk about literally anything else and we usually talk about soup, which is not work, which is the point.`,
    ],
    quote: `no agenda, the place with the broken sign`,
    footnote: `soup_judge. friday. the sign is still broken. thats how you know its us.`,
  },
  {
    slug: 'soup-is-soup-a-meal',
    title: 'is soup a meal (the ruling)',
    author: 'soup_judge',
    hour: 13,
    layout: 'bbs',
    tag: 'board',
    updated: '24 Feb 1999',
    search: 'soup meal ruling debate board food philosophy',
    teaser: 'He was asked to rule. He ruled. It took four paragraphs and landed somewhere unexpected.',
    paragraphs: [
      `i have been asked to rule on whether soup is a meal and as the closest thing this board has to an authority i accept the responsibility with the seriousness it does not deserve.`,
      `the case against: soup is a starter, a thing before a thing, you order it and then you order food. the case for: a good chowder with bread is more meal than half the sad desk sandwiches i have watched people call lunch.`,
      `here is the ruling. soup is a meal if you made it. if somebody handed you soup, it is a course. the labor is the meal-ness. a soup you stood over is dinner and a soup that arrived is an appetizer and the same bowl can be either depending entirely on whether you were tired when it was done.`,
      `this ruling is final and also i reserve the right to change it completely next friday if the chowder is good, because consistency is for machines and this is a food board run by a person who is, at the end of the day, mostly just hungry.`,
    ],
    footnote: `soup_judge. ruling: soup is a meal if you made it. 8 out of 10 as rulings go.`,
  },
  {
    slug: 'soup-the-end-seat',
    title: 'about the seat at the end',
    author: 'soup_judge',
    hour: 20,
    layout: 'bbs',
    tag: 'board',
    updated: '01 Apr 1999',
    search: 'end seat empty diner remember quiet march',
    teaser: 'The one time he addresses it directly, in his own sideways way.',
    paragraphs: [
      `ok. somebody new asked about the end seat again, kindly, and i said dont ask, and then i felt bad, so here, once, and then we go back to not.`,
      `the seat faces the door. it was somebody's seat, the way seats become somebody's without anyone deciding. and then that somebody stopped coming, around march, for reasons that are theirs and not the board's and definitely not a new person's to be handed on their first friday.`,
      `so we keep it clear. not as a shrine, nothing that heavy, we would all hate that. just clear. an empty chair that faces the door is a small way of saying the door still works, the seat is still here, and if you ever came back we would just slide over and make room and not say a word about it.`,
      `thats it. thats all i will say and more than i meant to. next week we are back to soup and the broken sign and whether the orange crackers count as a vegetable, which is a real debate we are having, and which is much more our speed.`,
    ],
    footnote: `soup_judge. we keep it clear. thats all.`,
  },

  // --- localhost_legend ---
  {
    slug: 'legend-my-cat',
    title: 'THE PAGE ABOUT MY CAT (finally)',
    author: 'localhost_legend',
    hour: 16,
    layout: 'card',
    tag: 'homepage',
    updated: '20 Mar 1999',
    search: 'cat page pet homepage promised finally photos',
    teaser: 'Promised on every under-construction page for months. It delivers, in its way.',
    paragraphs: [
      `THE CAT PAGE IS HERE!!! i have been promising this since like november and i finally figured out how to put a picture on a page except i could not find the picture so this is the cat page WITHOUT the picture for now but the words are here and the words are the important part probably.`,
      `my cat is named Modem which i named him before i knew modem was a computer thing, i just liked the sound, and then i got online and found out and now everyone thinks im Really into computers and i am but thats not why, its a coincidence, a Cool one.`,
      `Modem is orange and he sits on the warm part of the machine which is the top and he does not care about the internet at all which my mom says is a lesson and i said what lesson and she said exactly and i still dont get it but im writing it here in case future me does.`,
      `anyway thats the cat page. picture coming SOON (under construction!!!) but i wanted to get the words up because a promise is a promise even if its a little late, four months late, but the shovel guy is still digging so technically its been in progress the whole time.`,
    ],
    footnote: `Page about my cat. Picture coming soon!!! (the shovel guy agrees.)`,
  },
  {
    slug: 'legend-how-i-learned',
    title: 'HOW I LEARNED TO MAKE THE TEXT MOVE',
    author: 'localhost_legend',
    hour: 17,
    layout: 'card',
    tag: 'homepage',
    updated: '12 Feb 1999',
    search: 'marquee learned tutorial text move html help thanks',
    teaser: 'A triumphant follow-up to his desperate forum post. He wants everyone to know he did it.',
    paragraphs: [
      `I DID IT. the text moves now. after i posted asking for help and a guy explained it and i still got it wrong four times and then it WORKED and i yelled and my mom came in and i showed her and she said thats nice which for my mom is basically a standing ovation.`,
      `the secret is you put the words INSIDE the marquee thing, like a sandwich, the marquee is the bread. i was typing marquee and then the words next to it, not inside, and it just said marquee at the top of my page for three weeks and i thought that was how it looked for everyone.`,
      `so now the text goes across and it is the greatest thing i have ever made and i put ALL my text in it at first, the whole page moving, and a guy called lint_monk left me a very polite note that said this was, and i quote, a lot, and he was right, so now just the title moves. compromise. very mature of me.`,
      `THANK YOU to the guy who helped, i do not know your name but you changed my life and my page. if you are reading this, the text is moving right now because of you, and it will move forever, which is the closest thing to immortality a fifteen year old can give somebody.`,
    ],
    footnote: `The title moves now. Just the title. (lint_monk was right, do not tell him i said that.)`,
  },
  {
    slug: 'legend-webring-joined',
    title: 'I GOT INTO THE WEBRING!!!',
    author: 'localhost_legend',
    hour: 15,
    layout: 'card',
    tag: 'homepage',
    updated: '02 Apr 1999',
    search: 'webring joined accepted ring valley proud belong',
    teaser: 'Getting into the local webring is, to him, roughly equivalent to knighthood.',
    paragraphs: [
      `IM IN THE WEBRING. the valley one. you have to know somebody already in to join and i did not know anybody but i emailed the ring master todd like nine times being really polite and i think he let me in to make the emails stop but IM IN and that is what matters.`,
      `i am stop 12 now. you can get to my page by pressing Next on stop 11 which is the weather guy, so if you are reading the weather and you press next, you get ME, which means the weather guy and i are basically neighbors now, on the internet, which is a real place, do not let anyone tell you different.`,
      `i have the little ring banner at the bottom of my page now with Prev and Next and Random and i have pressed Random about a hundred times to see where i land and once i landed on a page that was nine minutes to load and i waited all nine minutes out of respect for the ring.`,
      `belonging to something is the best feeling and it turns out the something can be a list of homepages of people who argue at a diner on fridays and i have never met any of them but i am in their ring now and that counts, that absolutely counts, i checked.`,
    ],
    footnote: `Stop 12 in the valley webring!!! Press Next on the weather guy to find me.`,
  },

  // --- fax_aurora ---
  {
    slug: 'aurora-fire-door',
    title: 'MEMO: THE FLOOR 2 FIRE DOOR (SIXTH NOTICE)',
    author: 'fax_aurora',
    hour: 9,
    layout: 'fax',
    tag: 'memo',
    updated: '17 Mar 1999',
    search: 'fire door propped open memo sixth notice safety',
    teaser: 'The office has now raised the propped fire door in six consecutive memos. The tone is changing.',
    paragraphs: [
      `INTEROFFICE MEMO. RE: THE FLOOR 2 FIRE DOOR. THIS IS THE SIXTH CONSECUTIVE NOTICE ON THIS MATTER AND THE OFFICE WISHES THAT FACT TO BE FELT.`,
      `IT HAS BEEN OBSERVED, AGAIN, THAT THE FLOOR 2 FIRE DOOR IS PROPPED OPEN. IT WAS PROPPED OPEN IN JANUARY. IT WAS PROPPED OPEN IN FEBRUARY. IT IS, AT THE TIME OF THIS SCAN, PROPPED OPEN.`,
      `THE OFFICE UNDERSTANDS THAT THE STAIRWELL IS WARM AND THE DOOR IS HEAVY. THE OFFICE ALSO UNDERSTANDS WHAT A FIRE DOOR IS FOR, WHICH IS THE PART THAT KEEPS THE OFFICE WRITING THESE.`,
      `IF THE DOOR IS PROPPED OPEN AT THE SEVENTH NOTICE, THE OFFICE WILL BE FORCED TO IDENTIFY THE PROP, AND THE OFFICE HAS ITS SUSPICIONS ABOUT THE PROP, AND THE PROP KNOWS WHO IT IS.`,
    ],
    footnote: `PAGE 1 OF 1. THIS TRANSMISSION IS CONFIRMED COMPLETE. THE DOOR REMAINS OPEN.`,
  },
  {
    slug: 'aurora-timesheet',
    title: 'MEMO: TIMESHEETS, A CLARIFICATION',
    author: 'fax_aurora',
    hour: 10,
    layout: 'fax',
    tag: 'memo',
    updated: '04 Mar 1999',
    search: 'timesheets thursday clarification memo due office',
    teaser: 'Having conquered the message boards, the office issues a formal clarification of the Thursday deadline.',
    paragraphs: [
      `INTEROFFICE MEMO. RE: TIMESHEETS. A CLARIFICATION HAS BEEN REQUESTED AND THE OFFICE, THOUGH TIRED, PROVIDES ONE.`,
      `TIMESHEETS ARE DUE THURSDAY. THIS HAS BEEN STATED ON THE MESSAGE BOARDS, WHICH THE OFFICE JOINED SOLELY FOR THE PURPOSE, AND WHICH THE OFFICE HAS FOUND TO BE, AND THE OFFICE QUOTES ITSELF, QUITE INTERESTING IN HERE.`,
      `THE QUESTION RAISED WAS WHETHER THURSDAY MEANS THIS THURSDAY OR NEXT THURSDAY. THE ANSWER IS THURSDAY. THE OFFICE FINDS THE QUESTION REVEALING AND HAS MADE A SMALL PRIVATE NOTE OF WHO ASKED IT.`,
      `THE OFFICE WOULD LIKE TO ADD, OUTSIDE THE MATTER OF TIMESHEETS, THAT IT SEES THE BOARDS, IT SEES THE JOKES ABOUT SOUP, AND IT HAS, ON AT LEAST ONE OCCASION, FOUND THEM MILDLY AMUSING. THIS ADMISSION WILL NOT BE REPEATED.`,
    ],
    footnote: `PAGE 1 OF 1. THURSDAY. NOT FRIDAY. NO RESPONSE IS REQUESTED.`,
  },
  {
    slug: 'aurora-the-backup',
    title: 'MEMO: ON THE MATTER OF THE JANUARY BACKUP',
    author: 'fax_aurora',
    hour: 8,
    layout: 'fax',
    tag: 'memo',
    updated: '15 Mar 1999',
    search: 'backup january restore memo pages office careful',
    teaser: 'The office addresses the archive loss the only way it knows how, and something almost human leaks through.',
    paragraphs: [
      `INTEROFFICE MEMO. RE: THE RESTORATION OF SUBSCRIBER PAGES. THE OFFICE WRITES ON A MATTER OUTSIDE ITS USUAL SUBJECTS, WHICH ARE DOORS AND TIMESHEETS.`,
      `IT HAS BEEN ESTABLISHED THAT PAGES RESTORED AFTER THE MARCH LOSS CAME FROM A BACKUP OF SOME AGE. THE OFFICE CONFIRMS THIS. THE OFFICE DOES NOT CONFIRM THE AGE, BECAUSE THE OFFICE WAS NOT TOLD THE AGE, WHICH IS ITSELF A THING THE OFFICE HAS NOTICED.`,
      `THE OFFICE HAS PROCESSED A NUMBER OF FORMS FROM SUBSCRIBERS WHOSE PAGES CAME BACK CHANGED, OR CAME BACK SHORTER, OR DID NOT COME BACK. THE OFFICE HAS PROCESSED THESE FORMS CAREFULLY. THE OFFICE PROCESSES ALL FORMS, BUT IT PROCESSED THESE MORE SLOWLY, AND IT IS NOT REQUIRED TO SAY WHY.`,
      `THE OFFICE REGRETS THE LOSS. THE OFFICE NOTES THAT REGRET IS NOT AN ADMISSION AND THAT THE MEMO CONTAINS NO APOLOGY, PER GUIDANCE. THE OFFICE ALSO NOTES, IN THE LAST LINE, WHERE FEWER PEOPLE READ, THAT IT IS SORRY.`,
    ],
    footnote: `PAGE 1 OF 1. THIS TRANSMISSION IS CONFIRMED COMPLETE.`,
  },

  // --- lint_monk ---
  {
    slug: 'monk-the-count',
    title: 'Item: the mill fire figure',
    author: 'lint_monk',
    hour: 21,
    layout: 'report',
    tag: 'correction',
    updated: '02 Mar 1999',
    search: 'correction mill fire twelve nine number source',
    teaser: 'The corrections desk and the town historian arrive at the same fact from opposite directions.',
    paragraphs: [
      `Item 1. The widely posted figure of twelve men affected by the mill fire is, on the available evidence, wrong. The correct figure appears to be nine.`,
      `I quote the original, as I always do, because the original is the point: "twelve men lost everything the night the mill burned." Two errors in one sentence. The number, and the single night, when the record describes a slow burn over a winter.`,
      `My source is not my own research, which I do not have, but the town record kept by town_annals, who cites a payroll and an insurance filing. I note that I am relying on another person's sourcing, and I name them, because a correction that hides its source is just a second opinion wearing a badge.`,
      `I will add, and this is a rare thing for me to add, that I take no pleasure in this one. It is a better story with twelve and a single night. But a corrections desk does not get to keep the better story, and neither, I would gently suggest, does a town.`,
    ],
    footnote: `Corrections desk. Item filed. Source: town_annals, cited in turn. The number is nine.`,
  },
  {
    slug: 'monk-on-being-wrong',
    title: 'Item: a correction to a correction',
    author: 'lint_monk',
    hour: 23,
    layout: 'report',
    tag: 'correction',
    updated: '28 Mar 1999',
    search: 'correction wrong notice twelve admit desk error humility',
    teaser: 'The rare page where the corrections desk corrects itself, at length, and refuses to enjoy it.',
    paragraphs: [
      `Item 1. In a previous notice I corrected a subscriber's spelling of "definitely" while myself writing "occured" with one r. I quote my own original, as the rule requires, and the rule does not exempt me: "this occured on the board Tuesday."`,
      `Two people wrote to point it out, both politely, one clearly delighted. I have left my error up, as I leave all errors up, with the correction beneath it, because a corrections desk that quietly fixes its own mistakes is running a different and worse operation than the one I intend to run.`,
      `The temptation, and I will name it because naming it is the only defense against it, was to edit the original and pretend the r had always been there. I have watched other people do exactly that on this net, silently, after being caught, and it is the single thing I hold in the most contempt, so I could hardly do it myself.`,
      `Item 1, corrected: the word is "occurred", two r's, and it was I who got it wrong, and the notice stays up, and the delighted correspondent may consider themselves thanked, once, in writing, which is more than they will get from me twice.`,
    ],
    quote: `a corrections desk that quietly fixes its own mistakes is running a worse operation`,
    footnote: `Corrections desk. The error is mine and it stays up. Two r's.`,
  },
  {
    slug: 'monk-what-i-wont-do',
    title: 'Item: what this desk will not correct',
    author: 'lint_monk',
    hour: 22,
    layout: 'report',
    tag: 'correction',
    updated: '09 Apr 1999',
    search: 'corrections policy will not grief dialect voice refuse',
    teaser: 'A statement of limits from a man everyone assumes has none.',
    paragraphs: [
      `People assume, because I run a corrections desk, that I would correct anything, and I want to set out plainly the things I will not touch, because the limits are the whole character of the work.`,
      `I do not correct the way a person naturally speaks. localhost_legend writes in capitals and exclamation and his own spelling, and that is his voice, not an error, and a corrections desk that came for a person's voice would be a bully with a citation format.`,
      `I do not correct grief. There are pages on this net written by people who lost something in March, written badly, written in the wrong tense, written in sentences that fall apart at the end. Those are not errors. Those are the most accurate writing on the whole net, and I would sooner close the desk than mark them.`,
      `I correct facts that can be checked and mistakes the writer would want caught. That is the line. On one side, a wrong number in a public record, which I will pursue to the end of the earth. On the other, a person being themselves, or being sad, which is none of my desk's business and never will be.`,
    ],
    footnote: `Corrections desk. Facts, not voices. Errors, not grief. Nothing past that.`,
  },

  // --- town_annals ---
  {
    slug: 'annals-the-diner',
    title: 'The diner with the broken sign, a small history',
    author: 'town_annals',
    hour: 20,
    layout: 'broadsheet',
    tag: 'history',
    updated: '30 Mar 1999',
    search: 'diner broken sign history record local landmark friday',
    teaser: 'The historian turns her method on something small and living, and it holds up.',
    paragraphs: [
      `I usually record the mill and the founding and the losses, the large things, but a town is also its small standing places, so today the diner with the broken sign, which is a landmark by use if not by any register.`,
      `The sign has read the same broken word since at least 1991 (personal memory, mine, and three others who agree, which I mark as memory and not record). The owners could fix it. The owners have understood, correctly, that the broken sign is now the name, and that fixing it would erase a landmark to repair a sign.`,
      `A group meets there Fridays. I will not record who, or why the end seat stays empty, because some things are true without needing to be filed, and a historian's discipline includes knowing which truths are none of the record's business. I note only that the meeting exists and has for years.`,
      `I record the diner because in fifty years the mill will still be in the county register and the diner will not, and someone should have written down that a broken sign was a landmark and a Friday table was an institution. The register keeps the large things. A person keeps the diner.`,
    ],
    footnote: `Petersham Valley record. The diner with the broken sign, kept by use. (memory, cited as memory.)`,
  },
  {
    slug: 'annals-the-webring',
    title: 'The webring as a public record',
    author: 'town_annals',
    hour: 11,
    layout: 'broadsheet',
    tag: 'history',
    updated: '06 Apr 1999',
    search: 'webring record dead sites preservation history net',
    teaser: 'She makes an unexpected argument: the stubborn webring master is doing her job.',
    paragraphs: [
      `I want to record, and defend, a decision that most of the net treats as an annoyance: the webring master's refusal to remove the dead sites from the ring.`,
      `Members ask, reasonably, why pressing Next should sometimes land on a page that no longer loads. It is untidy. It is, they argue, broken. And the ring master declines, in one sentence, every time, and I have come to think he is the best historian on this whole net and does not know it.`,
      `A dead site left in the ring is a record that the site existed. Remove it and you have not fixed the ring, you have erased a person's page from the one place that still remembered it was there. The nine-minute load, the not-found, the stall: those are gravestones, and a webring that removed its gravestones would be tidier and would be lying.`,
      `So I record the ring master's stubbornness as preservation, whether he means it as that or simply as not wanting the bother. The effect is the same. Six dead sites stay findable because one man will not press delete, and in this he keeps the net's record better than the net keeps it itself.`,
    ],
    quote: `a webring that removed its gravestones would be tidier and would be lying`,
    footnote: `Petersham Valley record. The dead ring stops, defended as record. (the ring itself.)`,
  },
];
